### ISSUE TITLE
How do we select/deselect the items programmatically? 

### ISSUE THREAD

**Issue by cangokdayi** [Choices-js/Choices#1004]
I have this multiple choice Choices (v9.0.1) instance that I have no control of, it's initiated by a WP form builder plugin and we're adding extra functionalities to it. We've developed a custom selector element to hide the Choices element itself so we'll only use it in the background.   

I'd like to be able to select and deselect the available options programmatically. So let's say my custom selector element has a data attribute called "data-value" with the value "option-x" and when I click on it, my function will find the Choices item with the value "option-x" and click on it or call the proper method to select or deselect it. 

On Choices v9.0.1, triggering the 'mousedown' event on the Choices item does the job but it doesn't work on the newer versions of the library. setChoicesByValue() method doesn't seem to be doing anything as well. 

And for some reason, most of the methods I've tried on the console don't seem to be working (see screenshot below) is it because I'm trying to init an already initiated instance, or what I am doing wrong here? Any help is much appreciated, thank you. 

**Screenshots**
![console](https://user-images.githubusercontent.com/26194899/152662700-0fac75f2-a9a1-4927-a6a7-42425244567f.png)

**Comment by mtriff** [comment]
Can you provide a simplified jsFiddle or code examples? 

There's no reason that setChoicesByValue should not be doing what you're looking for (I assume you're using something like [removeActiveItemsByValue(value)](https://github.com/Choices-js/Choices#removeactiveitemsbyvaluevalue) when an option is deselected as well).

> is it because I'm trying to init an already initiated instance

Yes, this is why, you need to access the original Choices instance, or in your debugging, initialise it yourself in the console before the WP plugin does it.

**Comment by cangokdayi** [comment]
> Can you provide a simplified jsFiddle or code examples?

Thanks for the reply Matt. I was just setting up a [jsFiddle](https://jsfiddle.net/cangokdayi/d7yzaxt5/13/) for you and yeah you're right, the problem is that I'm trying to assign it to a new variable that's why it isn't working. 

Like I said, modifying the original instance isn't an option so do you think destroying and creating a new instance with the same values would be an option?

**Comment by cangokdayi** [comment]
For those who are having the same issue, that's how I've had fixed it.

1 - Found the JS file which the plugin dev creates the instance, copied the instance options and found what their selector was, in my case it was a class called "ff_has_multi_select" 

2 - Identified the handle of the JS file and dequeued it inside the get_footer action and enqueued my own JS file in between it so I can remove the selector of my element and initiate it myself before the plugin does, see below.

`add_action('get_footer', function(){

	wp_dequeue_script('fluent-form-submission');
	wp_enqueue_script('xc-fluent-form-custom-functions');
	wp_enqueue_script('fluent-form-submission');

}, PHP_INT_MAX);`

3 - Initiated the instance in my JS file with the same options I've copied from the plugin's own initiator. 


I know this only applies to WP but you can try that destroy and re-init idea I've mentioned above, good luck.
