### ISSUE TITLE
Choices AJAX

### ISSUE THREAD

**Issue by abhiatsisl** [Choices-js/Choices#1015]
Hi I want to integrate ajax with choices so when I type any word it will search from the ajax and show in the choices list,

Please help me out integrating this feature with ajax

**Comment by mtriff** [comment]
Choices hasn't been designed for remote search. For example, how would options appear if users don't type anything and use the dropdown instead?

You can instead load all items from a remote source with Ajax/Fetch and then let Choices handle the searching. [Here's an example](https://github.com/Choices-js/Choices/blob/master/public/index.html#L639) from our demo page. Example 2 on the [`setChoices` documentation](https://github.com/Choices-js/Choices#setchoiceschoices-value-label-replacechoices) is also an example of this approach.

**Comment by abhiatsisl** [comment]
Hey Matt,

If choices have the feature of Ajax searching then it's glad and very helpful of use, because sometime we have to load lots of data, Ajax searchin will optimize the load time

Regards,
Ahishek

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by xgrei** [comment]
select2 has implemented this function, but select2 uses jquery.

**Comment by taufik-nurrohman** [comment]
Try like this maybe:

~~~ js
example.setChoices(async () => {
  try {
    const items = await fetch('/api/search?query=' + encodeURIComponent(example.getValue(true)));
    return items.json();
  } catch (err) {
    console.error(err);
  }
});
~~~
