### ISSUE TITLE
wrong parameter type for setChoiceByValue

### ISSUE THREAD

**Issue by npolauer** [Choices-js/Choices#1017]
The Method "setChoiceByValue" expects an "string" as Parameter, but should expect "string | string[]" since it should be possible to pass  an Array as Parameter as well.

It forces an Type-Error on Typescript which you need to dodge using an "any" type, suppress the Error or use similar dirty hacks.

![image](https://user-images.githubusercontent.com/56922874/156573014-3543afc2-8cad-4350-92c3-a8239a82f849.png)
![image](https://user-images.githubusercontent.com/56922874/156573164-35efc8b1-8ffa-44a3-b325-2ea04bf4a397.png)

**Comment by mtriff** [comment]
Thanks for flagging this! It has been fixed on `master` and will be included in the next release.
