### ISSUE TITLE
How to clear selection?

### ISSUE THREAD

**Issue by umairayub88** [Choices-js/Choices#1037]
I'm creating a form which is submit using AJAX but after response I want to clear selection. I need a process or complete code how to clear selected value.

**Comment by kevinleto-informaticon** [comment]
Have you tried with `setChoicesByValue('') or setChoicesByValue([])`?
`''` for single-select
`[]` for multiple-select

**Comment by umairayub88** [comment]
Hi,

I have found this error " setChoicesByValue is not a function ".  And please share how to set the value. Need full code.

Regards

**Comment by kevinleto-informaticon** [comment]
Sorry, it was `.setChoiceByValue(...)` (without the 's').

You can try this:
```js
const element = document.getElementById('your_element_id');
const choices = new Choices(element);

// after the form submit
choices.setChoiceByValue([]);
```

You can find the doc [here](https://github.com/Choices-js/Choices#setchoicebyvaluevalue).
