### ISSUE TITLE
Multiple Select Fields will dont working

### ISSUE THREAD

**Issue by JDittmerCOM** [Choices-js/Choices#1038]
I have two <select> fields. Both have the tag "multiple".
With the first <select> everything works, but with the second only a simple list is shown.

How can I fix this to be the same as the first field?

Choices.js Version 10.1.0

![Bild_2022-05-22_145231377](https://user-images.githubusercontent.com/11929467/169696009-2e89ed64-dd40-4353-8620-8d44e18f85b4.png)

**Comment by MrMooky** [comment]
I just stumbled onto this as well. My code looks like this:

```
if (document.getElementsByTagName('select').length >= 1) {
    new Choices('select', {
        allowHTML: false,
        searchEnabled: false,
    });
}
```

Only the first select on the page is working. I'm also not sure what to make of this note in the docs:

> Note: If you pass a selector which targets multiple elements, the first matching element will be used. Versions prior to 8.x.x would return multiple Choices instances.

To me it basically sounds like that for each select there should be a new `Choices` instance created manually? That would be bad.

**Comment by Denisbeder** [comment]
Same here.

My solution for the moment

```
const items = document.querySelectorAll("[data-select]");

items.forEach((item) => new Choices(item));

**Comment by JDittmerCOM** [comment]
Thank you for the answers.

However, I found a solution for myself a long time ago.

```
if($('#choicesjs-gameserver-permissions')[0]){
	new Choices('#choicesjs-gameserver-permissions',
		{
			removeItemButton: true,
			searchEnabled: true,
			itemSelectText: '',
			allowHTML: true
		}
	);
}
```
