### ISSUE TITLE
How to get the selected choices in different parts of code?

### ISSUE THREAD

**Issue by PINHOf** [Choices-js/Choices#1044]
**Describe the bug**
The example given in https://github.com/Choices-js/Choices#getvaluevalueonly doesn't work for an existing / initialized Choices Element. How should I grab the values in different parts of my code?

**To Reproduce**
Lets say I have the following object:

```
var Ads = 
{
	init: function()
	{
		const select = document.getElementsByName('categories[]')[0];
		
		new Choices(select);
	},
	
	// How to grab here the values selected?
	save: function()
	{		
		const el = document.getElementsByName('categories[]')[0];
		
		// Doesn't work, it's initializing a new Choices
		const x = new Choices(el);
		const v = x.getValue(true);
		
		// Doesnt work, it doesn't catch an already initialized Choices 
		// Returns error: TypeError: Cannot set properties of undefined (setting 'config')
		const x = Choices(el);
		
		// Doesn't work, returns undefined 
		console.log(el.choices);
	}
};
```

**Expected behavior**
Grab Choices values in different parts of code.

**Works**
The only thing that works is common JS way. Am I forced to use this?
```
const elOptions = document.getElementsByName('categories[]')[0].selectedOptions;
const elValues = Array.from(elOptions ).map(({ value }) => value);
```

**Comment by mtriff** [comment]
You need to maintain a variable with the instance returned by the original call to the Choices constructor. In your case, this would happen within your `init` function, i.e.
```javascript
let choicesInstance = null;

var Ads = 
{
	init: function()
	{
		const select = document.getElementsByName('categories[]')[0];
		
		choicesInstance = new Choices(select);
	},
...
```
You can then use `choicesInstance.getValue()` elsewhere in your code.
