### ISSUE TITLE
Select doesn't preserve optgroups after destroying Choices instance

### ISSUE THREAD

**Issue by beyer96** [Choices-js/Choices#1055]
**Describe the bug**
I use Turbolinks in my app, so I need to destroy Choices instances everytime before Turbolinks caches the page. But when I destroy Choices instance on select with optgroups in it, these optgroups disappear in default select after destroying Choices.

**JSFiddle here**: https://jsfiddle.net/rjqzsum6/

I have workaround for this, in case someone else runs into this problem too. It replaces innerHTML of default select completely (but correctly, with optgroups): 

```
const destroyChoices = (choices, select) => {
  const newOptgroupArray = [];

  select.innerHTML = choices._presetGroups.forEach(optgroup => {
    const newOptgroup = document.createElement("optgroup");
    newOptgroup.label = optgroup.label;
    newOptgroup.innerHTML = optgroup.innerHTML;
    newOptgroupArray.push(newOptgroup);
  });

  choices.destroy();
  select.innerHTML = "";
  newOptgroupArray.forEach(newOptgroup => {
    select.appendChild(newOptgroup);
  });
};
```

But it would be really nice not to use this 'hotfix'

**Comment by Xon** [comment]
Implemented as part of #1166
