### ISSUE TITLE
Cannot use Choices if rendered from iframe

### ISSUE THREAD

**Issue by andreaskienast** [Choices-js/Choices#1057]
**Describe the bug**
Disclaimer: To be honest, this is a kinda special setup.

I have a modal window whose content contains a `select` field that is used to initialize Choices.js. There are two scopes where this modal may be opened:

* in a simple standalone view
* in a more complex environment with an `iframe`, where the modal is rendered in the *top* frame

In the latter case, I get the error "Expected one of the following types text|select-one|select-multiple". The issue is that the `instanceof` check for the passed element to initialize Choices.js does not work in case of an inter-frame communication. In my tests it was safe to check `passedElement.constructor.name` instead.

Since the fix is rather easy I'll push a PR ASAP.

**To Reproduce**
1. In the iframe, have a callback that initializes Choices.js
2. Open a modal with the matching `select` element on the top frame
3. Execute the callback
4. See "Expected one of the following types text|select-one|select-multiple"

**Expected behavior**
I expect that Choices.js works in the scenarios mentioned above.

**Desktop (please complete the following information):**
 - OS: Fedora Linux 36
 - Browser Chrome
 - Version 105

**Comment by seredniy** [comment]
+1. I have a similar problem.
