### ISSUE TITLE
Add support for ES Modules

### ISSUE THREAD

**Issue by jorgeparavicini** [Choices-js/Choices#1059]
Currently, the library only supports CJS modules. I am writing an angular wrapper, and using this library could cause optimization bailouts as described in the [angular docs](https://angular.io/guide/build#configuring-commonjs-dependencies).

To prevent this we need support for ES Modules. My understanding of this topic is limited, but as far as i understood, one could add a new tsconfig.esm.json file which targets the "es6" instead of "commonjs".

**Comment by sirenbrian** [comment]
+1

**Comment by Xon** [comment]
This has been implemented in v11.0.0. Not yet pushed to NPM
