### ISSUE TITLE
Auto submitting form after choice needs timeout?

### ISSUE THREAD

**Issue by stell** [Choices-js/Choices#1064]
So to make it simple:

```
const myselect = new Choices('#myselect', mySelectInit);
myselect.passedElement.element.addEventListener(
    'choice',
    (e) => {
        setTimeout(function () {
            document.getElementById('myForm').requestSubmit();
        }, 10);
    },
    false,
);
```
When not using the timeout, the new chosen value is not getting submitted.

Am I missing something?

**Comment by Xon** [comment]
You'll probably want the `addItem` even not the `choice` event, as the item probably hasn't been "committed" yet depending on the version of Choices being used.
