### ISSUE TITLE
Instantiate choices when select field added dynamically

### ISSUE THREAD

**Issue by creativetags** [Choices-js/Choices#1065]
I'm using Choices for select fields on a form and when one field is changed I do an AJAX request to the server and the server sends back another select field to add to the form. I need that field to be instantiated as a Choices select.

I'm instantiating my original fields with:

  const items = document.querySelectorAll('.js-choice');
  items.forEach((item) => new Choices(item));

but when I try to add something like that to my AJAX code it complains that Choices isn't defined and it won't let me import it again because I'm not calling from a js module.

Is there a way to watch for new .js-choice elements and instantiate automatically?

Also [posted to StackOverflow](https://stackoverflow.com/questions/74209993/instantiate-choices-js-when-select-field-added-dynamically)

**Comment by Xon** [comment]
You would need to update your AJAX code to setup the choices object after adding the field.
