### ISSUE TITLE
Given an element how can I get choice instance?

### ISSUE THREAD

**Issue by realnot** [Choices-js/Choices#1075]
I'm generating all choices instances on elements that have a 'data-choices' on application bootstrap. Then, I have to update choices set from API.

```js
const element = document.getElementById('id_city');
const choices = new window.Choices(element)
{#choices.setChoices(data['results'], 'pk', 'name', true);#}
choices.setChoices([
  { value: 'One', label: 'Label One', disabled: true },
  { value: 'Two', label: 'Label Two', selected: true },
  { value: 'Three', label: 'Label Three' },
]);
```

setChoices in this case will not work because an instance of choices is already initialized on 'element'. How can retrieve choices instance from 'element'?

**Comment by b3wii** [comment]
+1

**Comment by Hel5ing** [comment]
+11111

**Comment by Xon** [comment]
This requires infrastructure outside choices to track the HTML elements and javascript object relationships, and is well outside the scope of what this project can offer

**Comment by vladdancer** [comment]
Here is a simple widget registry for Choices lib - https://gist.github.com/vladdancer/7f8283afac83f09984cd22e7ec9a6ff2
Just import it with your favorite bundler and then register widget `ChoiceWidgetRegistry.createWidget(element, {});`
then access it another place with `const widget = ChoiceWidgetRegistry.getWidget(element)`
Note: there is no destroy()/dispose() methods for the moment.
