### ISSUE TITLE
Add item in `select` and `select multiple`

### ISSUE THREAD

**Issue by belingheri-riccardo-wise** [Choices-js/Choices#1078]
**Is your feature request related to a problem? Please describe.**
I want a `select` or `select multiple` with possobility by the user to create items like type `text`
![image](https://user-images.githubusercontent.com/77446070/205277601-533c9a82-0097-48e0-b5e7-a451aa717be2.png)

**Describe the solution you'd like**
Support tag [addItems](https://github.com/Choices-js/Choices#additems) in input type `select` an `select multiple`.

The value written by the user is the value and the visualizated text

**Describe alternatives you've considered**
A botton near to che arrow-down to add value if [addItems](https://github.com/Choices-js/Choices#additems)  is `true`

**Additional context**

**Comment by kabirpathak** [comment]
This feature has been previously addressed in [!525](https://github.com/Choices-js/Choices/pull/525).

**Comment by belingheri-riccardo-wise** [comment]
Duplicate issue, main issue #525
