### ISSUE TITLE
Not a bug report: how to use multiple select without having it to add the selections?

### ISSUE THREAD

**Issue by stratboy** [Choices-js/Choices#1079]
Hi, I would need to use `<select multiple>` with choices.js. But I'd like to disable the selections reporting (pillbox). This because I don't want pills. I want to just write a text like '2 of 10 where selected'.
I can't find proper options to pass.
Are there any?

**Comment by fayekramzy91** [comment]
I'm looking for the same feature. Any workaround solution?

**Comment by stratboy** [comment]
Hi, in the end, I used select2.js as all do. I think that currently is the best... Choice..

**Comment by Xon** [comment]
This isn't supported
