### ISSUE TITLE
type wrongful character in the selection box

### ISSUE THREAD

**Issue by ousmorez** [Choices-js/Choices#1080]
**Describe the bug**
While dropdown is closed, it opens after entering a key like (down arrow) but it prints "arrow Down" on the combo box. We should stop writing values that are more than one character on the select boxes or combo boxes.

**To Reproduce**
1. Go to [Choicejs](https://choices-js.github.io/Choices/)
2. Click on 'Right-to-left'
3. Select 'Choice1'
4. enter Arrow Down
It will type it into the select box.

**Expected behavior**
We expect not to type anything in the select box.

**Screenshots**
![aa](https://user-images.githubusercontent.com/50699824/205452537-06830700-4aec-4aa8-abb1-344e9850ae29.gif)

**Desktop (please complete the following information):**

-OS: Windows 10
-Browser: Chrome
-Version: Latest

**Comment by Xon** [comment]
Fixed as part of #1116

**Comment by neurotools** [comment]
It's possible to backport this fix to the 10.x branch?

Some projects, including Laravel Filament 3.x depend on this branch and due to breaking changes in 11.x branch will not update the dependency.

**Comment by Xon** [comment]
There has been significant code churn in the v11.0.0+ update, and the fix ended up being significantly more complicated than the linked PR
