### ISSUE TITLE
Can't Set Placeholder

### ISSUE THREAD

**Issue by brandon-9** [Choices-js/Choices#1082]
It appears that when using `setChoices()`, you can't set a placeholder for Select fields?

Any support on that front would be greatly appreciated!

**Comment by kabirpathak** [comment]
Facing the same issue.

**Comment by gdebrauwer** [comment]
I'm also facing this issue. It seems very weird behavior that the placeholder is not used when using `setChoices`

**Comment by ludekbenedik** [comment]
Solution for version 10.2.0 (maybe earlier version too).
```
const choices = [
    { value: '', label: 'Select value', placeholder: true },
    { value: 'a', label: 'A' },
    { value: 'b', label: 'B' },
];
choicesJs.setChoices(choices, 'value', 'label', true);
```

**Comment by Xon** [comment]
`loadingText` is what is used when setChoices is loading data.
