### ISSUE TITLE
Remove arrow

### ISSUE THREAD

**Issue by jparadaa** [Choices-js/Choices#1089]
Hi, I implemented an example to use Choices and it works fine, I just want to know if it is possible to remove the arrow (I show it in the attached image), I have noticed that the arrow does not display if you use the multiple option, but in my case I am not using the multiple option, is there any way for me to remove the arrow?

![img1](https://user-images.githubusercontent.com/72886084/210021695-2c7beda4-affc-4bf5-bcfd-354740902dd4.png)

```
<div class="container">
    <div class="row">
      <div class="col-sm-6 mt-2">
        <label for="choices-single">Cliente</label>
        <select
          class="form-control"
          name="choices-single"
          id="choices-single"
          placeholder="This is a placeholder" >
          <option value="">Selecciona Cliente</option>
        </select>
      </div> <!-- col -->
    </div> <!-- row -->
</div> <!-- container -->
```

I appreciate your help

Regards,
Javier

**Comment by MatheusRich** [comment]
I guess you could hide it with CSS:

```css
.choices[data-type*=select-one]::after {
  display: none;
}
```
