### ISSUE TITLE
Loading choices without <select> html elements

### ISSUE THREAD

**Issue by jinyeng** [Choices-js/Choices#1095]
Is it possible to initialize choices without <select> html elements ? i.e. purely from  JavaScript without having to create html markups  ?

**Comment by mtriff** [comment]
Yes, see the [`choices` parameter](https://github.com/Choices-js/Choices#choices) or [`setChoices()`](https://github.com/Choices-js/Choices#setchoiceschoices-value-label-replacechoices). See the examples [here](https://github.com/Choices-js/Choices/blob/master/public/index.html#L746-L764).

**Comment by jinyeng** [comment]
@mtriff In the provided example though, it is initialized with an element: new Choices('#**choices-single-no-search**', { 

and there is an html element created choices-single-no-search. My question was, if there is a way to render the choices without creating an html select element.
