### ISSUE TITLE
Set the selected option by user in Laravel

### ISSUE THREAD

**Issue by moatasem0** [Choices-js/Choices#1096]
I'm using Choices.js with laravel. When the user selects an option and submits the form something might go wrong and I need to show the values he selected the same thing with editing I need to select the one the user selected.

code:

`
var choices = new Choices($('.choices')[0], {
                delimiter: ",",
                editItems: true,
                maxItemCount: -1,
                removeItemButton: false,
               choices: {!! $countries !!}
            });
`

This works but I can't set the selected option by the user after the page refresh or on the edit page. I tried `setValueByChoice` and `setValue` but had no success.

I tried to load all the options with html but it's showing numbers only no text.

`<select class="choices" name="country">
    <option></option>
    @foreach ($countries as $country)
        <option value="{{ $country->id}}">{{ $country->name}}</option>
    @endforeach
</select>`

**Comment by Xon** [comment]
`setChoiceByValue` would work, but it needs the exact id/value being passed to it, not the label/name.

You need to select the `selected` attribute on the relevant `<option>`. Similarly for the `choices` array via javascript.
