### ISSUE TITLE
Menu not closing in item click or click outside --- only in Safari

### ISSUE THREAD

**Issue by atstockland** [Choices-js/Choices#1100]
**Describe the bug**
Menu exposes when clicked on, as expected, however does not close after clicking an item or clicking outside the menu.  Even the DEMO page suffers from this.  I have confirmed this issue does not exist in Chrome or FireFox.  It seems to only exist in Safari.

**To Reproduce**
1. Go to the choices.js DEMO page on Safari, expose the "Multiple select input" or any select menu that exposes a dropdown (like Option groups).
2.  Notice the menu area will not close after selecting an item or clicking outside of the menu

**Expected behavior**
Safari should act the same as the other browsers

**Desktop (please complete the following information):**
 - OS: MacOS
 - iOS: this also occurs 16.1.1
 - Safari 16.1

**Comment by belabedmedoussama** [comment]
you should add this to your css code 
```
.choices__list--dropdown{
.....
....
transform: translate3d(0, 0, 200px);
}
```

**Comment by atstockland** [comment]
Thanks @belabedmedoussama.  That solution does work to fix the issue.  It seems like a bug in the library though, that shouldn't require any css tweaks.  My app is working better thanks to you suggestion.

**Comment by ezitisitis** [comment]
Looks like a duplicate of: https://github.com/Choices-js/Choices/issues/1056
