### ISSUE TITLE
removeActiveItems method - excludedId should be optional?

### ISSUE THREAD

**Issue by beyer96** [Choices-js/Choices#1116]
Hello,

not sure if this should be considered as bug (if not, sorry!), but I think `removeActiveItems` should take `excludedId` parameter as optional. 

Correct me if I'm wrong, but I use this method with no parameter and no issues. Now, I have to use it with Typescript which yells at me that this method needs argument. I suppressed it of course, but it would be nice not have to do so :)

Thanks for any response!

**Comment by Xon** [comment]
That does make sense, and it is quite a small change. Implemented for the v11.0.0 release
