### ISSUE TITLE
Unlimited searchResultLimit

### ISSUE THREAD

**Issue by muendlein** [Choices-js/Choices#1118]
Having a fixed searchResultLimit is often not desirable as it makes assumptions about the data contents. In particular some matching results may be cut if the search limit is set to low.

Thus it would be good to display the search results with a scroll bar in order to avoid any fixed limit.

**Comment by joffreypersia** [comment]
Like `searchResultLimit: -1`

**Comment by Xon** [comment]
Implemented as part of #1166
