### ISSUE TITLE
duplicateItemsAllowed not working

### ISSUE THREAD

**Issue by alicericci** [Choices-js/Choices#1123]
It's not possible to select the same items twice dispite duplicateItemsAllowed default being true.

```html
  <select multiple>
    <option value="Choice 1">Choice 1</option>
    <option value="Choice 2">Choice 2</option>
    <option value="Find me">Choice 3</option>
    <option value="Choice 4">Choice 4</option>
  </select> 
```

```javascript
const element = document.querySelector('select');
const choices = new Choices(element, {
  editItems: true,
  renderSelectedChoices: "always",
});
```

**Expected behavior**
When clicked, Choice 2 is added to the list even if it's already selected 

<img width="453" alt="Screenshot 2023-06-15 at 15 07 08" src="https://github.com/Choices-js/Choices/assets/43652271/1609ceac-cbe0-4c2d-a951-d91ae9594160">

**Comment by Xon** [comment]
This is a documentation issue, as `duplicateItemsAllowed` only works with `text` and not `select-multiple`

**Comment by Xon** [comment]
This is a v11 regression (as pointed out in #1268), v11.0.4 will re-enable support for this
