### ISSUE TITLE
Accessibility problems - Google PageSpeed 

### ISSUE THREAD

**Issue by bystrzan** [Choices-js/Choices#1126]
**Describe the bug**
Google PageSpeed test - Accessibility problems. Test results showing low Accessibility score.

**To Reproduce**
1. Go to https://pagespeed.web.dev/analysis/https-choices-js-github-io-Choices/b8p9vahvue?form_factor=mobile
2. Look at the Accessibility tab

**Comment by Xon** [comment]
This should be resolved with the pre-release build of v11.0.0 which has been deployed
