### ISSUE TITLE
Choices does not behave like other HTML elements in a disabled fieldset

### ISSUE THREAD

**Issue by tagliala** [Choices-js/Choices#1132]
**Describe the bug**
It is expected that HTML elements are disabled in a globally disabled `fieldset`

Ref: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/fieldset#attributes

> If this Boolean attribute is set, all form controls that are descendants of the `<fieldset>`, are disabled, meaning they are not editable and won't be submitted along with the [`<form>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/form). They won't receive any browsing events, like mouse clicks or focus-related events. By default browsers display such controls grayed out. Note that form elements inside the [`<legend>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/legend) element won't be disabled.

**To Reproduce**
1. Go to https://jsfiddle.net/tagliala/yetk9sgh/13/

**Expected behavior**
Choices.js appears and behave like a disabled fieldset

**Screenshots**

<img width="702" alt="image" src="https://github.com/Choices-js/Choices/assets/556268/3991883a-14f0-444b-8e9d-afa5ad4d5ff5">

**Desktop (please complete the following information):**
 - OS: macOS 13.5.2
 - Browser Chrome / Safari / Edge
 - Version: latest

**Additional context**
On Firefox, the element is not interactable but it looks like an interactable field

**Workaround**

```js
  callbackOnInit: function () {
    // Workaround for Choices-js/Choices#1132
    if (this.passedElement.element.closest('fieldset:disabled')) {
      this.disable()
    }
  },
```

**Comment by Xon** [comment]
Implemented as part of #1166
