### ISSUE TITLE
iOS Firefox Virtual Keyboard / Disappearing Options Issue

### ISSUE THREAD

**Issue by andrewjknox** [Choices-js/Choices#1133]
**Describe the bug**
On iOS Firefox (it's okay on) the options disappear once the virtual keyboard disappears. It's an issue because sometimes you need to scroll the page to see the remaining options in the dropdown.

**To Reproduce**
Test with a multiple select control with several options. Open Firefox on iOS and click inside the input so that the keyboard appears. Scroll the page with your finger. Keyboard disappears and so does the dropdown of options.

**Expected behavior**
For the dropdown to remain so the user can select options.

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro
 - OS: iOS 16.6.1
 - Browser Firefox
 - Version 119.1

**Additional context**
Absolutely fine in the other browsers I have installed on my phone; Safari, Chrome and DuckDuckGo.

**Comment by Xon** [comment]
This should be fixed with v11.0.0
