### ISSUE TITLE
Search input outside the dropdown elements

### ISSUE THREAD

**Issue by przemekgoczal** [Choices-js/Choices#1136]
Is there an option or solution to get search input from dropdown elements, such as in select multiple, but in select single?

Now in single select, we have to open dropdown with options and then we can use input search.
I'd like to get this input search outside this dropdown like in multiple select

**Comment by Xon** [comment]
I plan to make this an option in v11.0.0. Feature needs testing and more documentation

**Comment by wpinfusion** [comment]
@Xon Is this already possible? I am unable to find any references to this feature in the Github docs, but I see in the demo that it's possible (See the Discogs api example).

In this example, the search input is inside `.choices-inner` as a sibling element to the `<select>` field.
I'm using the same version (11.0.2), but on my instance the search input is inside the `.choices__list` element.

**Comment by Xon** [comment]
@wpinfusion have a look at the [singleModeForMultiSelect](https://github.com/Choices-js/Choices#singlemodeformultiselect) config option

**Comment by jakenuts** [comment]
I'm a huge fan of this idea but singleModeForMultiSelect doesn't seem to have any effect on the location of the search input in 11.0.2.

**Comment by Xon** [comment]
Pass in `maxItemCount: 1` in the configuration object.

It doesn't derive that when in `select-single` mode, as it requires explicitly setting in `select-multiple` mode
