### ISSUE TITLE
Can I add a choice that not existing in the choices (multiple select)

### ISSUE THREAD

**Issue by henryonsoftware** [Choices-js/Choices#1137]
**Is your feature request related to a problem? Please describe.**
I want to build a tags feature but I only have a limited number of choices, I want to allow user to add more choices.

**Describe the solution you'd like**
Just search the choice user want, if empty then allow to add to the list

I'm not sure if we are supporting it or not, I can't see that option in the docs.
If you know, please help
If we don't have that option, let consider this is a feature request.
Thank you!

**Comment by charlielodder** [comment]
There is an open PR: https://github.com/Choices-js/Choices/pull/1117

**Comment by Xon** [comment]
Implemented as part of #1166
