### ISSUE TITLE
Wrong handling of ampersand in option text 

### ISSUE THREAD

**Issue by jprusch** [Choices-js/Choices#1138]
**Ampersand is HTML-escaped without need ( & -> & amp;)**

**To Reproduce**
Create a single select like:
```
<select name="search" class="choiceselect">
    <option value="1234">K&K</option>									
</select>
```
Check the rendered list. It displays as K& amp;K

Remark: I intentionally added a space after & to get this rendered correctly in github.

Generated HTML is:
```
<div id="choices--search-x1-item-choice-1" class="choices__item choices__item--choice choices__item--selectable is-highlighted"
   role="option" data-choice="" data-id="1" data-value="1234" data-select-text="" 
   data-choice-selectable="" aria-selected="true">K&amp;K</div>
```

**Expected behavior**
The select option displays: K&K

All browser & platforms affected (Windows /Chrome&Edge, iOS Safari)

<img width="149" alt="image" src="https://github.com/Choices-js/Choices/assets/9337414/fc8d33ee-eb49-4740-9e8d-60f2c49ed917">

**Comment by lucaspedreira** [comment]
allowHTML: true

**Comment by jprusch** [comment]
Thx, solved the issue
