### ISSUE TITLE
How can I access original option elements from the callbackOnCreateTemplates?

### ISSUE THREAD

**Issue by stratboy** [Choices-js/Choices#1149]
Hi, I'm trying to retain some data-props that are setted in the original select dom element, to persist them in choices and items. I'm having quite an hard time in doing this.

Is it possible? I just need a reference to the origina option element related to the current template item/choice.

**Comment by Xon** [comment]
I also missed it, but the readme.md has an example of touching the default templates to adjust the output similar to:
```
const example = new Choices(element, {
  callbackOnCreateTemplates: () => ({
    input: (...args) =>
      Object.assign(Choices.defaults.templates.input.call(this, ...args), {
        type: 'email',
      }),
  }),
});
```
