### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by stratboy** [Choices-js/Choices#1150]
Is it?

**Comment by Syfele** [comment]
Up Up Up

**Comment by rallisf1** [comment]
Both @mtriff and @jshjohnson have been inactive for over a year and I don't think anyone else has publish rights for this package. I was about to use it myself on a project but changed my mind.

**Comment by stratboy** [comment]
Anyway, because select2 is jquery dependent and also doesn't play really well (at least in my project) with js module system, I finally used Choices and I must say it's way better in every aspect, at least to me. So still reliable for production use.

**Comment by crstauf** [comment]
Last [release for select2](https://github.com/select2/select2/releases) was 2020, so Choices is still the better option (even without considering no jQuery dependency).

**Comment by Alexbrazdasilva** [comment]
If the author or any collaborator on the project speaks out, I am available to help. Make CR and even implement some of the features of some of the open issues.

**Comment by marcelfolaron** [comment]
Happy to help as well. For the time being we forked it and merged a PR to allow adding choices. 
https://github.com/Leantime/Choices

npm package is available as well

**Comment by Xon** [comment]
I've got my own fork that I've been updating to address bugs and some other issues;
https://github.com/Xon/Choices.js

**Comment by Xon** [comment]
I've been added as a maintainer, and plan todo v11.0.0 beta/rc release early next week and will be closing out issues as they are fixed.

**Comment by stratboy** [comment]
> I've been added as a maintainer, and plan todo v11.0.0 beta/rc release early next week and will be closing out issues as they are fixed.

You're my Hero!

**Comment by TimVerheul** [comment]
@Xon thank you
