### ISSUE TITLE
The width of the choices__list element is limited to the width of the initial div.choices

### ISSUE THREAD

**Issue by headkit** [Choices-js/Choices#1159]
The width of the _choices__list_ element is limited to the width of the initial _div.choices_ and forces its contents to wrap.

Is there a way to prevent this? It would be great if the width depends on the longest option entryof the list.

thnx!

**Comment by marcelfolaron** [comment]
Was able to solve that by setting `width: max-content;` on 
```
.choices__list--dropdown,
.choices__list[aria-expanded],
.is-open .choices__list--dropdown,
.is-open .choices__list[aria-expanded]
` ``
