### ISSUE TITLE
Remove recommendation for polyfill.io as it is no longer considered safe to use

### ISSUE THREAD

**Issue by marcusx** [Choices-js/Choices#1160]
The README recommends 

https://github.com/Choices-js/Choices/blob/5dbea2825a5887d88d6947443f4874bb7b84cc3a/README.md?plain=1#L1115

This is no longer considered safe to use. 

See: 

- https://polykill.io/
- https://twitter.com/triblondon/status/1761852117579427975
- https://blog.cloudflare.com/polyfill-io-now-available-on-cdnjs-reduce-your-supply-chain-risk

**Comment by alanhamlett** [comment]
#1161

**Comment by jurgenhaas** [comment]
I guess, the link doesn't need to be removed, it could be replaced with a save alternative, e.g. from fastly.

**Comment by alanhamlett** [comment]
No, it's dangerous even mentioning polyfill and no longer needed.

**Comment by BramDriesen** [comment]
> it's dangerous even mentioning polyfill

Not sure where that's coming from. It's not like you can just drop it. There is an safe alternative so let's use that, no?

**Comment by alanhamlett** [comment]
Implemented with #1161
