### ISSUE TITLE
Add Item on Select

### ISSUE THREAD

**Issue by noctivityinc** [Choices-js/Choices#1164]
**Is your feature request related to a problem? Please describe.**

Very much so.  When an item is not in the select list we need an option to let them add the typed string.  This is common practice in things like select2

**Describe the solution you'd like**

`addItem: true` should be supported for `select` lists and then the addItem event should just accept whatever was entered just like with `list = text`

**Describe alternatives you've considered**

Adding a new button next to the list, which is a weird UX for people to stop to have to click it

**Additional context**

If you cant do this easily, at least add support for the No items Found label to trigger an event that we can then use to handle this.

**Comment by noctivityinc** [comment]
It seems like all we would really need here is an event around line 863 in choices.ts to make this happen, right?

**Comment by Xon** [comment]
I've been working on a fork which implements this; https://github.com/Xon/Choices.js

My fork doesn't have the testing pipeline setup, but in the examples and my own usage it doesn't appear to be hitting noticeable bugs.

I've just tagged a release for the https://github.com/Xon/Choices.js/releases/tag/v11.0.0RC1

**Comment by noctivityinc** [comment]
@Xon two issues Im seeing:

1. When you create something new, it gets appended to the text box instead of replacing it.

![Screenshot 2024-08-02 at 9 34 10 AM](https://github.com/user-attachments/assets/edeeb6c3-ec92-4442-965a-518557ae773f)
(Build above was the first option, the `This is new` was the new option I typed and hit enter)

2. There is no indication int he addItem event fired that this is a new item. I need to either check that label is an object or the like.  Would be a good idea to maybe have a flag.

**Comment by noctivityinc** [comment]
It looks like the previous selected item is not being removed:

![Screenshot 2024-08-02 at 9 42 38 AM](https://github.com/user-attachments/assets/431d2274-7a32-4815-836f-43139de3085b)

**Comment by Xon** [comment]
It looks like there is a bug with the `select-one` and the item entering.

I've largely been using `select-multiple` with the new `singleModeForMultiSelect` flag.

**Comment by noctivityinc** [comment]
@Xon let me know when fixed and Ill be happy to continue my testing.  Great work so far!

**Comment by Xon** [comment]
I believe I've fixed the `select-one` bugs, but there is some undesirable/buggy behavior I'm not going to be able to easily fix. If you do find any more issues, please open an issue on [my fork's repo](https://github.com/Xon/Choices.js).

The new select choice code was something I merged in from an outstanding pull request, and runs into limitations of how `choices.js` is doing the UI control for that aspect.

Essentially it needs an explicit state machine to control were and how input is being processed and the various UI states it enables/disables. This sadly is something which need more time to be worked on.

**Comment by noctivityinc** [comment]
Thanks. Was there an alternative library you considered instead of this you think is worth looking at?

**Comment by Xon** [comment]
@noctivityinc I've tagged https://github.com/Xon/Choices.js/releases/tag/v11.0.0RC4 which contains bugfixes for various `select-one` issues you experianced.

I've been granted merge access to this repo and I'm working through fixing the broken tests and getting the above changes merged in.
