### ISSUE TITLE
Choices.js removeItem, reset and Remote date with custom template Fixed

### ISSUE THREAD

**Issue by mohanprabhus** [Choices-js/Choices#1168]
Check the Codepin for fixingChoices.js removeItem, reset and Remote date with custom template it might be useful for new comers.

https://codepen.io/mohanprabhus/pen/yLdzebQ

let me know if you face any issue

**Comment by Xon** [comment]
[v11.0.0](https://github.com/Choices-js/Choices/pull/1166) which hasn't been merged yet makes reloading choices from existing HTML makes this much easier in that you just need to set `select.innerHtml` and then call `choices.refresh()`.

**Comment by mohanprabhus** [comment]
@Xon  would give an example select.innerHtml and then call choices.refresh().  if possible can you check and share an update https://codepen.io/mohanprabhus/pen/yLdzebQ

**Comment by Xon** [comment]
Your approach works if the remote API is returning json. But if it is returning HTML, then the `refresh` method will be useful

This is basically how it would get used:
```html
choices.passedElement.element.innerHTML = select.innerHTML;
choices.refresh();
```

**Comment by mohanprabhus** [comment]
sugegst any worked around of my code my controller public function fetchData(Request $request)
    {
        try {
            $request->validate([
                'per_page' => 'sometimes|integer|min:1|max:100',
                'search' => 'sometimes|string|max:255',
                'page' => 'sometimes|integer|min:1'
            ]);

            $perPage = $request->input('per_page', 10);
            $search = (string) $request->input('search', '');
            $page = $request->input('page', 1);

            $query = CountriesIsdCode::query();

            if ($search) {
                $query->where('country_name', 'like', $search . '%');
            }

            $countries = $query->select('id', 'country_name', 'country_flag')
                              ->paginate($perPage, ['*'], 'page', $page);

            return response()->json([
                'pagination' => [
                    'page' => $countries->currentPage(),
                    'pages' => $countries->lastPage(),
                    'per_page' => $countries->perPage(),
                    'items' => $countries->total(),
                    'urls' => [
                        'last' => $countries->appends(['per_page' => $perPage])->url($countries->lastPage()),
                        'next' => $countries->appends(['per_page' => $perPage])->nextPageUrl(),
                    ]
                ],
                'releases' => $countries->items()
            ]);
        } catch (\Exception $e) {
            Log::error('Error fetching countries: ' . $e->getMessage());
            return response()->json(['error' => 'Internal Server Error'], 500);
        }
    } when im using custom template 
            callbackOnCreateTemplates: function(template) {
                return {
                    item: function({ classNames }, data) {
                        const isPlaceholder = !data.value; // Check if the current item is the placeholder

                        return template(`
                            <div
                                class="${classNames.item} ${data.highlighted ? classNames.highlightedState : classNames.itemSelectable}"
                                data-item
                                data-id="${data.id}"
                                data-value="${data.value}"
                                ${data.active ? 'aria-selected="true"' : ''}
                                ${data.disabled ? 'aria-disabled="true"' : ''}
                            >
                                ${data.customProperties && data.customProperties.flag ? `<img src="${window.location.origin}/${data.customProperties.flag}" alt="${data.label}" title="${data.label}" style="width: 22px; height: 17px; margin-right: 5px;border: 1px solid #0d1130;">` : ''}
                                ${data.label}
                              ${!isPlaceholder ? `<button type="button" class="choices__button" aria-label="Remove item: '${data.value}'" data-button>Remove item</button>` : ''}
                            </div>
                        `);
                    },
                    choice: function({ classNames }, data) {
                        return template(`
                            <div
                                class="${classNames.item} ${classNames.itemChoice} ${data.disabled ? classNames.itemDisabled : classNames.itemSelectable}"
                                data-select-text="${this.config.itemSelectText}"
                                data-choice
                                ${data.disabled ? 'data-choice-disabled aria-disabled="true"' : 'data-choice-selectable'}
                                data-id="${data.id}"
                                data-value="${data.value}"
                                ${data.groupId > 0 ? 'role="treeitem"' : 'role="option"'}
                            >
                                ${data.customProperties && data.customProperties.flag ? `<img src="${window.location.origin}/${data.customProperties.flag}" alt="${data.label}" title="${data.label}" style="width: 22px; height: 17px; margin-right: 5px;border: 1px solid #0d1130;">` : ''}
                                ${data.label}
                            </div>
                        `);
                    },
                };
            } , initially there is no search ( need to show 5 or 10 results) when i search data will search but when i click removeButton Item then it does not show initial value  so im overriding the initial value and clearing the search value check the script `document.addEventListener('DOMContentLoaded', () => {

    const element = document.querySelector('#countrycode');
    let lastValidSelection = null;  // Store last valid selection
    let isInitializing = false; // Flag to check if initialization is in progress

    if (element) {
        const countryChoices = new Choices(element, {
            allowHTML: true,
            removeItemButton: true,
            placeholder: true,
            placeholderValue: 'Choose...',
            searchPlaceholderValue: "Search",
            resetScrollPosition: true,
            shouldSort: false,
            position: 'auto',
            callbackOnCreateTemplates: function(template) {
                return {
                    item: function({ classNames }, data) {
                        const isPlaceholder = !data.value; // Check if the current item is the placeholder

                        return template(`
                            <div
                                class="${classNames.item} ${data.highlighted ? classNames.highlightedState : classNames.itemSelectable}"
                                data-item
                                data-id="${data.id}"
                                data-value="${data.value}"
                                ${data.active ? 'aria-selected="true"' : ''}
                                ${data.disabled ? 'aria-disabled="true"' : ''}
                            >
                                ${data.customProperties && data.customProperties.flag ? `<img src="${window.location.origin}/${data.customProperties.flag}" alt="${data.label}" title="${data.label}" style="width: 22px; height: 17px; margin-right: 5px;border: 1px solid #0d1130;">` : ''}
                                ${data.label}
                              ${!isPlaceholder ? `<button type="button" class="choices__button" aria-label="Remove item: '${data.value}'" data-button>Remove item</button>` : ''}
                            </div>
                        `);
                    },
                    choice: function({ classNames }, data) {
                        return template(`
                            <div
                                class="${classNames.item} ${classNames.itemChoice} ${data.disabled ? classNames.itemDisabled : classNames.itemSelectable}"
                                data-select-text="${this.config.itemSelectText}"
                                data-choice
                                ${data.disabled ? 'data-choice-disabled aria-disabled="true"' : 'data-choice-selectable'}
                                data-id="${data.id}"
                                data-value="${data.value}"
                                ${data.groupId > 0 ? 'role="treeitem"' : 'role="option"'}
                            >
                                ${data.customProperties && data.customProperties.flag ? `<img src="${window.location.origin}/${data.customProperties.flag}" alt="${data.label}" title="${data.label}" style="width: 22px; height: 17px; margin-right: 5px;border: 1px solid #0d1130;">` : ''}
                                ${data.label}
                            </div>
                        `);
                    },
                };
            }
        });

        const perPage = 10; // Adjust as needed

        async function fetchData(searchTerm = '', page = 1) {
            let url = `/countries?page=${page}&per_page=${perPage}`;
            if (searchTerm) {
                url += `&search=${searchTerm}`;
            }

            try {
                const response = await fetch(url);
                if (!response.ok) {
                    throw new Error(`HTTP error! Status: ${response.status}`);
                }
                const data = await response.json();
                return data.releases.map(country => ({
                    label: `+${country.country_isd_code} (${country.country_name})`,
                    value: country.country_isd_code,
                    customProperties: {
                        flag: country.country_flag,
                    }
                }));
            } catch (error) {
                console.error('Error fetching data:', error);
                return []; // Return empty data as a fallback
            }
        }

        async function initializeChoices() {
            isInitializing = true;
            try {
                const countries = await fetchData(); // Fetch data without search initially
                if (!countries.length) {
                    console.error("No countries data available.");
                    countries.push({ value: '', label: 'No countries available', disabled: true });
                } else {
                    // Ensuring the placeholder is set only once
                    const defaultOptionExists = element.querySelector('option[value=""]');
                    if (!defaultOptionExists) {
                        const defaultOption = document.createElement('option');
                        defaultOption.value = '';
                        defaultOption.disabled = true;
                        defaultOption.selected = true;
                        defaultOption.textContent = 'Choose...';
                        element.appendChild(defaultOption);
                    }
                }
                countryChoices.setChoices(countries, 'value', 'label', true);
            } catch (error) {
                console.error('Error initializing choices:', error);
                countryChoices.setChoices([{ value: '', label: 'Failed to load data', disabled: true }], 'value', 'label', true);
            } finally {
                isInitializing = false;
            }
        }

        element.addEventListener('search', async function(event) {
            const searchTerm = event.detail.value;
            const choices = await fetchData(searchTerm);
            countryChoices.setChoices(choices, 'value', 'label', true);
        });

        element.addEventListener('removeItem', function(event) {
            const selectedValues = countryChoices.getValue(true);
            if (!selectedValues || !selectedValues.length) {
                countryChoices.clearStore(); // Clear the internal state
                countryChoices.setChoices([{ value: '', label: 'Choose...', disabled: true, selected: true }], 'value', 'label', true);
                initializeChoices();
            }
        });

        element.addEventListener('addItem', function(event) {
            lastValidSelection = event.detail.value;
        });

        element.addEventListener('hideDropdown', function() {
             countryChoices.clearInput(); // Clear the search input when dropdown is hidden
        });

        element.addEventListener('showDropdown', async function() {
            if (lastValidSelection) {
                await initializeChoices();
                countryChoices.setChoiceByValue(lastValidSelection);
            } else {
                await initializeChoices();
            }
        });

        initializeChoices();
    } else {
        console.error('Element #countrycode not found in the DOM.');
    }

});`
