### ISSUE TITLE
[aria-*] attributes do not match their roles

### ISSUE THREAD

**Issue by hans2103** [Choices-js/Choices#1169]
**Describe the bug**
While performing accessibility check using Lighthouse I get the following message in the results:

```
[aria-*] attributes do not match their roles
```

**To Reproduce**
1. Go to https://choices-js.github.io/Choices/
2. Open Dev Tools
3. Click on tab = lighthouse
4. Perform Accessibility check 
5. See error / warning

**Expected behavior**
Expecting [aria-*] attributes to match their roles

**Screenshots**

![Screenshot 2024-08-16 at 13 46 29](https://github.com/user-attachments/assets/40b3700a-1dc6-467f-b1fc-bae49d6bb79f)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hans2103** [comment]
adding `role="option"` to the elements that use `aria-selected="true"` will solve the issue. 

> while native HTML _option_ elements that are descendants of a _select_ can only be set as being _selected_, elements with an explicit _option_ role can not only allow the equivalent _aria-selected_, but also the _aria-checked_ attribute, supporting widgets/constructs that go beyond the capabilities of a native _select_ element.

source: https://www.w3.org/TR/html-aria/#aria-semantics-that-extend-and-diverge-from-html

**Comment by Xon** [comment]
@hans2103 thanks, I've merged that into my fork which will be pushed to my v11.0.0 PR after the weekend. I'm still working through some of the e2e tests, so `main` on my fork may be broken.

The [diff for this change](https://github.com/Xon/Choices.js/commit/5eb8680883c0136224560e335bf21d85c42ada77#diff-bc0be08a0cd7a73fbd4cf6cd89612b879ad88890ff36399d9c6346570030ec27) isn't complicated but I only have the ability to merge other people's PRs not my own :(

**Comment by Xon** [comment]
It ended up touching a few more bits, but lighthouse accessibility score is reporting between 92 to 100 depending on the exact test page. Well better than the previous 72 or lower.

Obviously no substitute for real testing with a screen-reader.

One of the changes is to apply `aria-label` by extracting a matching `<label for>` which references the backing element's id.
