### ISSUE TITLE
clearStore not work

### ISSUE THREAD

**Issue by kannerban** [Choices-js/Choices#1180]
clearStore() items are not resetting correctly when I use this method. When I select an option, it adds a new item instead of resetting to the initial state.
![Screenshot 2024-08-29 111807](https://github.com/user-attachments/assets/4240d752-b7b0-4061-b46e-5a969a922c88)

**Comment by Xon** [comment]
It is actually a bug in the `refresh` which it is preserving previous selections, and the `setChoiceByValue` method not respecting the single selection when restoring the initial configuration.

**Comment by Xon** [comment]
It was `clearStore`. It wasn't pruning the item list UI after the performance fixes around very large number of times.

I've got a fix, just want to confirm all the end-to-end tests still pass, including the new one to rest the form reset functionality
