### ISSUE TITLE
[v11] missing `style` package export for webpack based asset pipelines

### ISSUE THREAD

**Issue by tagliala** [Choices-js/Choices#1184]
## Describe the bug
Hello, I'm trying to upgrade a working app using shakapacker (a pre-processor based on webpack) to Choices v11 but I'm getting an error related to scss import

When updating from Choices.js 10 to Choices.js 11, shakapacker is not able
to resolve
- `@import "choices.js/src/styles/choices";` in Scss
- `import "choices.js/public/assets/styles/choices.css";` in JS

This is due to the new `exports` entry in `package.json`, which require
specific entries for webpack, such as `style`

### Tools and versions required to replicate

- npm 10.8.0
- Shakapacker 7/8
- Node 20.15.0
- Ruby 3.3.4 (should not be relevant)
- Rails 7.2.1 (anything >= 6.1.0 should not be relevant)

### Initial app
```sh
rails _7.2.1_ new test-choices-package-exports --skip-active-record --skip-javascript --skip-git --skip-test
cd test-choices-package-exports
echo "{ \"private\": true, \"packageManager\": \"npm@10.8.2\" }" > package.json
echo "gem 'shakapacker', '8.0.2'" >> Gemfile
bundle
rails shakapacker:install
npm add css-loader style-loader mini-css-extract-plugin css-minimizer-webpack-plugin
npm add choices.js@10.2.0
echo "module.exports = { plugins: [require('postcss-import')] }" > postcss.config.js
git add .
git commit -am "First commit"
git branch tests/scss main
git branch tests/css main
```

#### CSS import from JavaScript
```
git checkout tests/css
echo "import \"choices.js/public/assets/styles/choices.css\";" >> app/javascript/packs/application.js
git commit -am "CSS test"
bin/shakapacker # WORKS, CSS OUTPUT PRESENT
npm add choices.js@^11.0.0
bin/shakapacker # DOES NOT WORK
```

Error:
```
ERROR in ./app/javascript/packs/application.js 16:0-53
Module not found: Error: Package path ./public/assets/styles/choices.css is not exported from package ./node_modules/choices.js (see exports field in ./node_modules/choices.js/package.json)
```

#### Sass

```
git checkout tests/scss
npm add sass-loader sass
echo "@import \"choices.js/src/styles/choices.scss\";" >> app/javascript/packs/application.scss
git add .
git commit -am "Scss test"
bin/shakapacker # WORKS, CSS OUTPUT PRESENT
npm add choices.js@^11.0.0
bin/shakapacker # DOES NOT WORK
```

Error:
```
Error: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
Can't find stylesheet to import.
  ╷
1 │ @import "choices.js/src/styles/choices.scss";
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  app/javascript/packs/application.scss 1:9  root stylesheet
```

### Suggested solution

https://github.com/ifad/Choices/tree/bugfix/style-export

1. `npm add choices.js@ifad/choices#bugfix/style-export`
2. Retry `bin/shakapacker`

Details are in the commit message

Ref: https://webpack.js.org/guides/package-exports/#reference-syntax

**Comment by Xon** [comment]
@tagliala Can you try the `webpack-css` branch? This appears to be the `"sideEffects": false` being an overly big hammer for webpack [ref](https://stackoverflow.com/a/49776306)

**Comment by tagliala** [comment]
Hello, unfortunately this does not work with my specific use case, but I can also see that fontawesome's package.json contains `sideEffects` entries for `.css` and `.scss`. 

I've tried

1. `@import "choices.js/src/styles/choices";`
2. `@import "choices.js/src/styles/choices.scss";`
3. `@import "choices.js";`

And the error is always the same

```
Error: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
Can't find stylesheet to import.
   ╷
30 │ @import "choices.js/src/styles/choices.scss";
   │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
```

Back in 2022, when Font Awesome 6 was released, we had to deal with a lot of use cases and asset pipelines. I can still still provide a script to create a reproducible test case, but that would be specific to Rails, Ruby, webpack, shakapacker. Let me know if it is the case

However, according to our finding back at the times, the following commit should contain all the necessary parts to make webpack work and prevent tree-shaking issues:

https://github.com/ifad/Choices/commit/6a532c05737caa5b08c953e7ae50882707f60e9d

Please also check the side effects

**Comment by Xon** [comment]
Can you try using the following syntax against the proposed PR?
```
@import '~choices.js/src/styles/choices.scss'
```

The `~` is a bit of webpack syntax which I believe will made it pull the stylesheet from the node_modules path. You'll need `sass-loader`/`sass` configured in webpack.

**Comment by tagliala** [comment]
Hi,

> The `~` is a bit of webpack syntax which I believe will made it pull the stylesheet from the node_modules path. You'll need `sass-loader`/`sass` configured in webpack.

I do have those, but using `~` was an old deprecated way of referencing modules used until 2022

Ref: https://webpack.js.org/loaders/sass-loader/#resolving-import-at-rules

> Using ~ is deprecated and should be removed from your code, but we still support it for historical reasons. Why can you remove it? The loader will first try to resolve @import as a relative path. If it cannot be resolved, then the loader will try to resolve @import inside [node_modules](https://webpack.js.org/configuration/resolve/#resolvemodules).

Ref: https://github.com/diowa/ruby3-rails6-bootstrap-heroku/commit/370f74950fd1c77fcdcf3bc5bae7db3fb3a4c830

I've get rid of all `~`s in my projects a couple of years ago.

Unfortunately we had a lot of struggles with `exports` entry and webpack. And I understand the resistance to including changes in package.json

Ref: https://github.com/fnando/i18n/issues/91#issuecomment-1944208527

---

Said so, I will provide you the script that I've used in Font Awesome when we had to deal with this `package.json` entry and webpack(er) based asset pipelines. Please allow me some time (I will create a new comment)

**Comment by Xon** [comment]
@tagliala Can you create a PR for your requested changes?

**Comment by tagliala** [comment]
@Xon Yes I can, I'm now investigating also `css` support, dedicated `sass` support, and it requires a little bit of time. I will use this issue to post updates and eventually open a PR

**Comment by tagliala** [comment]
# WORK IN PROGRESS

### Tools and versions required to replicate

- choices.js 11 (10.x is unaffected)
- yarn classic 1.22.22
- Shakapacker 7/8
- Webpack 5
- Node 20.15.0
- Ruby 3.3.4 (should not be relevant)
- Rails 7.2.1 (anything >= 6.1.0 should not be relevant)

### Actual behavior

When updating from Choices.js 10 to Choices.js 11, shakapacker is not able
to resolve `@import "@import "choices.js/src/styles/choices";` anymore

```
Can't find stylesheet to import.
   ╷
30 │ @import "choices.js/src/styles/choices";
   │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
  app/javascript/stylesheets/choices.scss 30:9  @import
  app/javascript/packs/application.scss 5:9     root stylesheet
```

This is due to the new `exports` entry in `package.json`, which require
specific entries for webpack, such as `style`

### How to reproduce

```sh
$ rails _7.2.1_ new test-choices-package-exports --skip-active-record --skip-javascript --skip-git --skip-test
$ cd test-choices-package-exports
$ echo "{ \"private\": true, \"packageManager\": \"yarn@1.22.22\" }" > package.json
$ echo "gem 'shakapacker', '8.0.2'" >> Gemfile
$ bundle
$ rails shakapacker:install
$ yarn add css-loader style-loader mini-css-extract-plugin css-minimizer-webpack-plugin sass-loader sass
$ echo "module.exports = { plugins: [require('postcss-import')] }" > postcss.config.js
$ yarn add choices.js@10.2.0
$ echo "@import \"choices.js/src/styles/choices\";" > app/javascript/packs/choices.scss
$ bin/shakapacker # WORKS
$ yarn upgrade choices.js@^11.0.0
$ bin/shakapacker # DOES NOT WORK
```

### Cause

The cause is the new `exports` field in `package.json`. Apparently it is tricking
webpack and it is not able to solve choices.js's stylesheet

### Suggested solution

https://github.com/ifad/Choices/commit/6a532c05737caa5b08c953e7ae50882707f60e9d

Plus a breaking change in the Sass file

```diff
-@import "choices.js/src/styles/choices";
+@import "choices.js";
```

Details are in the commit message

Ref: https://webpack.js.org/guides/package-exports/#reference-syntax
