### ISSUE TITLE
input text - method setValue no longer works on version 11.0.2

### ISSUE THREAD

**Issue by climmmm** [Choices-js/Choices#1207]
**Describe the bug**
Since the latest version v11.0.2, the “setValue” method no longer works on input text.

**To Reproduce**
1. Create a choice instance on a input text
2. Call setValue. For example : choiceElt.setValue(['test', 'test2']);
3. See that input has no values

**Choices version and bundle**
- Version: v11.0.2

**Additional context**
No problem with v10.2.0

**Comment by mediaessenz** [comment]
I have exact the same issue and it seems to be fixed and merged.
But how do I get the fixed version?
With "choices.js": "^11.0.2", in my package.json the bug still exists!

**Comment by Xon** [comment]
I've been busy with other projects, so haven't found the time to build a new release

**Comment by kdaguenet** [comment]
I just downloaded 11.0.3 with the fix but it seems that the setValue still doesn't work. I went back to 10.2.0 and it works perfectly.

**Comment by cespare** [comment]
This bug should probably be reopened since it is definitely still broken.

**Comment by JuanAlessandrini** [comment]
yeap, is still not working.

**Comment by Xon** [comment]
Can you recreate a [Minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) using https://jsfiddle.net ?
