### ISSUE TITLE
Dropdown list items rendered multiple times when bulk adding options

### ISSUE THREAD

**Issue by adamsro** [Choices-js/Choices#178]
It seems that `render()` is called every time a choice is added and render removes all innerHTML DOM elements from the dropdown and recreates the list leading to poor performance with large sets, O(n2).

`setChoices` calls `_addChoice` in a loop which in turn calls `store.dispatch` and store calls render on every state change. 

The pattern seems to look like: render 1 - clear - render 1, render 2 - clear render 1, render 2, render3

**Comment by jshjohnson** [comment]
Hey! 

There is certainly room for improvement here. There is also going to need to be a loop within the `render()` method but I'm wondering whether it would be better to dispatch to the store with a bulk of data...

**Comment by adamsro** [comment]
Hi! Idk, the bulk dispatch seems to make the most sense to me, `ADD_CHOICES` and `REPLACE_ITEMS` or something. I like the idea of only making one call to update the state per user/api interaction. If `render` is only called once there's less reliance on the state checks within the function.

**Comment by adamsro** [comment]
Using https://github.com/google/incremental-dom or https://github.com/patrick-steele-idem/morphdom Mmight be a nice way to improve rendering performance (less GC), particularly while searching since many choice results will remain the same as more search characters are added?

**Comment by MicroDreamIT** [comment]
How to import if you use webpack, its saying, 

`import  {Choices} from 'choices.js/assets/scripts/src/choices';`

error:

`Uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'`

But if i use this way nothing is happening,

```
window.Choices = require('choices.js');

new Choices('#portTag',{
    
});
```

error look like,

`Uncaught TypeError: Cannot read property 'type' of null`

**Comment by jshjohnson** [comment]
@MicroDreamIT If you have installed Choices via npm, you just need to do this:

```import Choices from 'choices.js'```

**Comment by flying-sheep** [comment]
please add the `pinned` label or whatever makes @stale shut up.

**Comment by jshjohnson** [comment]
@flying-sheep can you provide a jsfiddle demonstrating Choices affecting load time please? Would be interested to know the size of your dataset too.

**Comment by jshjohnson** [comment]
I've got a functioning work-in-progress of Choices using morphdom. Would be great if somebody could take it for a spin. The branch name is `integrate-morphdom`

**Comment by flying-sheep** [comment]
looking good! sadly I have not time to compare times, so how much did they improve?

if you e.g. provide 10000 choices to select from, the JS needed a few seconds to execute before. is that zippy now?

**Comment by flying-sheep** [comment]
@stale no
