### ISSUE TITLE
Make select options enable/disable state reflect on choices element

### ISSUE THREAD

**Issue by petermonte** [Choices-js/Choices#531]
There are many old issues that surround this issue but I can't find one that solves my problem.
Please assume this as a Question. 

## This is the problem:
When I make an `option`, from my `select` element, `disabled` it has no impact on the `Choices` rendered element. In fact I just lost all my `options` from the `select` element.

## This is the context:
I'm using vue.js to manage my select elements. This means initialising several `select` elements that relate with each other. A specific selection on a first `select` must determine what is `disabled` on the following ones. After this, the form is submitted to server with all `options` and all states.

My vue.js script is bind to each `select` meaning that any manipulation is done on the select part and not on the rendered `.choices` element. But any change to the `select` element is completely ignored.  When inspecting on Chrome, the `select` element suffers a sever manipulation from **Choices** script to the point that all its `options` are removed except the selected one.

Is this intentional?
Is it actually a good practice, given the fact that one might want to assume the `select` element as the container to report to server?
If not, then why do we even bother to bind a `select` element from the beginning?

Feedback/help is much appreciated.

**Comment by firestar300** [comment]
Same issue on React.

**Comment by syu93** [comment]
Hi,
I had the the same issue using Vue.js for multiple select, by the way Choices operate, it breack the native behaviour of v-model. So to override this issue, I had to use the choices inner state to remove all active items and then select them back if needed.

It goes like that
```javascript
  // ...
  watch: {
    value(value) {
      // Need to manualy set the selected choices value
      // As it remove the natural behaviour of select element
      if (Array.isArray(value)) {
        this.choices._currentState.items.map(item => this.choices.removeActiveItemsByValue(item.value));
      }
      this.choices.setChoiceByValue(value);
      this.selectValue = value;
    }
  },
}
```
