### ISSUE TITLE
setChoiceByValue function triggers "change"  Event 

### ISSUE THREAD

**Issue by jkeller92** [Choices-js/Choices#561]
Like the title says.
In Documentation you can see that it should not be triggered.
I had a hard time to work around that. I hope it will be fixed in future

**Comment by mannok** [comment]
I am suffering from this too... please fix...

**Comment by fede91it** [comment]
+1

**Comment by eballeste** [comment]
setChoiceByValue should be triggering the `choice` event but it isn't.
