### ISSUE TITLE
Placeholder not displayed for empty dropdown

### ISSUE THREAD

**Issue by ckotzbauer** [Choices-js/Choices#567]
I use choices in single-select mode and set `placeholder: true, placeholderValue: 'a string'`. The placeholder is not displayed in UI if there are no choices. When I add choices later, the placeholder is displayed correctly.
This happens with version 7.0.0

**Comment by Colin-Moran** [comment]
I came across this problem since choices.ClearStore() also removes the placeholder item. The solution I'm using is this:  

`
        placeholderItem = choices._getTemplate(
        'placeholder',
        'This is a placeholder'
    );
    choices.itemList.append(placeholderItem);
`

Where 'choices' is the name of your choices object.

**Comment by hg64** [comment]
Possibly same issue.... Using clearChoices. Getting a javascript error intermittently on line 2630 placeholderItem.innerHTML = this._placeholderValue || '';

        if (this._isSelectOneElement) {
             placeholderItem.innerHTML = this._placeholderValue || '';
        } else {
          this.input.placeholder = this._placeholderValue || '';
        }

**Comment by ipavlyk** [comment]
This is an issue: ![image](https://user-images.githubusercontent.com/6399701/58150208-93d57f00-7c6e-11e9-987b-a41363f5eeb8.png)

**Comment by TeraNovaLP** [comment]
@jshjohnson I have the same problem. Is there any update yet?

**Comment by vitobotta** [comment]
Hi @jshjohnson I am having this issue now. I am fetching items with async ajax and one of the elements returned has the property selected set to true. Is there a fix or workaround for this? Thanks!

@hg64 @Colin-Moran  @code-chris  pinging you guys too in case you have found a proper solution for this.

**Comment by Xon** [comment]
Implemented as part of #1166
