### ISSUE TITLE
Mobile Firefox doesn`t search in selects

### ISSUE THREAD

**Issue by dmitriipol1** [Choices-js/Choices#616]
only on mobile version Firefox 
and only on letters - select doesn`t search items.
it can be reproduced on Choices demo page.

**Comment by florianbrinkmann** [comment]
I’m experiencing the same. If it helps for solving the issue: For me the filtering works when I insert two spaces after a word.

**Comment by itailitai** [comment]
Any solution?

**Comment by dominik-zen** [comment]
Same issue on Firefox 68.1.1., android 9. Works as expected on everything else I've tested, mobile or desktop.

Like with space, adding chars like `/ | - *` after the text will also trigger the search.

**Comment by itailitai** [comment]
Any one have a solution?

**Comment by dessalines** [comment]
I'm also still getting this. The FF nightly doesn't have this issue tho.
