### ISSUE TITLE
setChoices() should use fetchFromObject()

### ISSUE THREAD

**Issue by BlaM** [Choices-js/Choices#626]
When adding elements through ajax() you can specify "object.attribute" identifiers (with "dot" notation) as source for value or label. For that the function _ajaxCallback() uses fetchFromObject() to fetch child attributes from objects.

https://github.com/jshjohnson/Choices/blob/061219cb0035f24a34e2541da142f42d54c8bd95/src/scripts/choices.js#L1026

I would expect setChoices() to behave the same way, but it does not. It just uses `groupOrChoice[value]`.

https://github.com/jshjohnson/Choices/blob/061219cb0035f24a34e2541da142f42d54c8bd95/src/scripts/choices.js#L433

**Comment by jshjohnson** [comment]
Would you be able to open a PR addressing this please? 🙏

**Comment by BlaM** [comment]
Can I do that without having the full build environment? 

I usually just work with ES5 JavaScript and currently don't have enough time to learn more about newer ES dialects and BabelJS. Maybe some time next year :fearful:
