### ISSUE TITLE
A kind of fuzzy search

### ISSUE THREAD

**Issue by spong-e** [Choices-js/Choices#680]
HI, I am loving the library but have 1 requirement that I cant seem to meet. Basically, I am using the library for an occupation list, one of the requirements is that if a user enters "IT" this should search for any entries with IT but also any that include "Computer". Is this possible via the existing solution?

This is possible using the select2 library using the ```matcher``` function.

Thanks

**Comment by spong-e** [comment]
Hi, Ive looked into ```fuseOptions``` on the fuse site but couldnt see how it was possible. Im trying to replace a server side call with a pure JS component. So basically, what I need is given the list...
```
["Computer programmer", "Farmer", "IT Technician"]
``` 
If the user enters "IT" into search box then I need to return "Computer programmer" and "IT Technician".

Im also limited in that I cant change the shape of the data to add extra properties, eg, tags, etc which I could see how fuse would be able to use.

**Comment by tinovyatkin** [comment]
Is it hard coded list of items? I mean how do you know that `IT` is related to `Computer programmer`?

**Comment by spong-e** [comment]
Sorry, I explained it poorly. So what currently happens is, when the phrase ```IT``` (and variants of) is detected, then "computer" is added a search term, so effectively the list is search for job titles that start with either of those.

**Comment by tinovyatkin** [comment]
Ok, you need to have some sort of hidden tags also? You may add tags to `customProperties` and then use [searchfields](https://github.com/jshjohnson/Choices#searchfields) option
