### ISSUE TITLE
RTL css is not working properly for selected value in dropdown.

### ISSUE THREAD

**Issue by sriram275** [Choices-js/Choices#689]
With your RTL css everything is working except selected value is not working which is still positioning in left.  So is there way to not include RTL css so we will conver by using RTLcss convertor.
![image](https://user-images.githubusercontent.com/7270651/67483119-b850df80-f682-11e9-9f28-3597021e61d8.png)

Thanks.

**Comment by tinovyatkin** [comment]
@sriram275 below is screenshot from [demo page](https://joshuajohnson.co.uk/Choices/#choices-single-rtl) and it shows everything correctly (the only problem in current version is scrollbar position):
![Screenshot 2019-10-27 at 15 12 59](https://user-images.githubusercontent.com/5350898/67639925-571c4c80-f8cc-11e9-905f-002ad2ea927e.png)
Are you applying some extra CSS?
Did you set `dir=rtl` attribute on original SELECT element?

**Comment by tinovyatkin** [comment]
@sriram275 Could you check whether this problem is fixed for you in recently released Choices 8?
