### ISSUE TITLE
Event strange behavior

### ISSUE THREAD

**Issue by cedbesafilm** [Choices-js/Choices#712]
If i enable removeItemButton and attach choice and removeItem event listener these are the results

- when i press the removeItemButton removeItem event is triggered
- when i select a choice both choice and removeItem events is triggered (first change and last removeItem)

This is a big problem for my app, it set value to a var depending on the event and so it's buggy

If i attach only the change event when i press removeItemButton the change event is triggered two times.
This case is much better then above but i think it's a bug too cause the event has to be triggered only one time

this is my setup

var list = document.querySelectorAll(selector);

    	list.forEach(function(select) {
    		window['select_' + select.id] = new Choices(select, {
    			removeItemButton: true,
    			searchEnabled: false,
    			searchFields: ['label'],
    			searchResultLimit: 10,
    			noResultsText: "Nessun risultato trovato",
    			itemSelectText: '',    
    			fuseOptions: {
    			      include: 'score',
    			      threshold: 0
    		    }
    		});
    		
    		select.addEventListener("change", function(e) {
    			console.log("CHANGE");
    			console.log(e);
    		}, false);

    		/*select.addEventListener("choice", function(e) {
    			console.log("CHOICE");
    			console.log(e);
    		});

    		select.addEventListener("removeItem", function(e) {
    			console.log("REMOVE");
    			console.log(e);
    		});*/
    	});

**Comment by tinovyatkin** [comment]
@cedbesafilm do you see the same behaviour if you creating just one instance of Choices on a page?

**Comment by cedbesafilm** [comment]
Yes the same behaviour happens even with just one instance of Choices.

In my test with change event i noticed the after the first event has fired the getValue() method return undefined (and so i 'discard' the event in code), after the second event getValue() return "" that is the value i'm expect

![image](https://user-images.githubusercontent.com/55377336/67684566-b5f8c900-f993-11e9-8636-e306ac453cf6.png)

**Comment by tinovyatkin** [comment]
@jshjohnson I think that's fixed by change in #697 
@cedbesafilm can you try with version from `master`?
```sh
npm i jshjohnson/Choices#master
```

**Comment by cedbesafilm** [comment]
I'm using v7.1.5 from jsdelivr.net
I download the version from npm and the file in the asset folder are the same (except for the fuse part) so i think that i'm using the latest version

**Comment by tinovyatkin** [comment]
we have non-released changes in `master` branch of this repository, that's why I'm asking for test.

**Comment by cedbesafilm** [comment]
With version from master (redownloaded just now) i have the same issues with change event and choice/removeItem both with one or more instance of Choices

**Comment by Xon** [comment]
Logic around how events are emitted got overhauled as part of v11.0.0
