### ISSUE TITLE
Custom attributes striped from select options

### ISSUE THREAD

**Issue by DieterGribnitz** [Choices-js/Choices#738]
I have a select list that requires custom data attributes to be read from the selected option on change.
If an item is selected a function runs using the custom option data.
If I apply the lib to a select list all options are striped out and all data attributes are removed.
Is there a way to keep the data attributes intact on the options?
If not, can you point me to where the option in being constructed?

Thanks.

**Comment by tinovyatkin** [comment]
@DieterGribnitz there is no way to keep them with the current version of Choices, but you can recreate them by overriding `option` property on `callbackOnTemplateCreate`

**Comment by DieterGribnitz** [comment]
Thanks I will give it a try.

**Comment by MatthieuWinalist** [comment]
Is there still no easy way to do this ? Thanks.

**Comment by DuyTr** [comment]
How can I re-write this in JS, not Typescript? Thank you
