### ISSUE TITLE
Create extra option for placeholder option value

### ISSUE THREAD

**Issue by mkatrantzis** [Choices-js/Choices#769]
I believe theres value in adding an extra option which would allow you to choose the value (as opposed to the text that the current placeholderValue attribute is setting) of the placeholder. This I believe should be part of a bigger work that would set the value of the widget to the value of the placeholder when all options are removed (create "invisible" option with the set value). A scenario that I personally encountered issues with the current setup is when I put a multiple select in a form and I clear all values. Serialising or submitting the form you will see that theres no value for the select (not even an empty value) and this makes handling the clearing of the data on the server side considerably harder.

**Comment by tinovyatkin** [comment]
You can do it right now by overriding templates via `onCreateTemplatesCallback`

**Comment by mkatrantzis** [comment]
@tinovyatkin Thanks for the reply. I ended up doing it like so..

`

       const select = new Choices(widget, {
            maxItemCount: max,
            placeholder: true,
            placeholderValue: placeholder,
            .....


       select.passedElement.element.addEventListener('removeItem', function(event) {
            if(select.getValue().length==0){
                var el = select.setValue(['']);
                el.itemList.element.childNodes[0].classList.add('hidden');
            }
        });

        // Add event listener to select all options available when 'All' is clicked
        select.passedElement.element.addEventListener('addItem', function(event) {
            const value = event.detail.value;
            // If it was empty remove the empty value
            if(this.length>1 && this[0].value==''){
                select.removeActiveItemsByValue('');
            }
           .....
`
