### ISSUE TITLE
Option not to show partial search matches if exact matches are found

### ISSUE THREAD

**Issue by olszowka** [Choices-js/Choices#776]
I am using the "select-one" configuration of choices.  My lists have hundreds of entries and many typical searches will result in dozens of exact matches of the search term.  I believe users will want to type into the search box until they see a short list.  However, because the exact matches are followed by partial matches, users can't see at a glance they have only a few exact matches.

I'd like to see a configuration parameter to enable suppression of partial matches why any (or possibly a specified number) of exact matches are found.

**Comment by alanhamlett** [comment]
Duplicate of #454.
