### ISSUE TITLE
Not supported by IE

### ISSUE THREAD

**Issue by besciualex** [Choices-js/Choices#802]
Hi,

It is not supported by IE v.11.165.17134.0

There are errors on IE 11:
- it doesn't recognize Array.includes() and neither Array.from ( I added polyfills for them, therefore it is not that critical) 
- after the polyfills quick fix it gives a new error: _Object doesn't support property or method 'findIndex'_ for line **var firstEnabledChoiceIndex = choices.findIndex(function (choice) {**

**Comment by kl3sk** [comment]
Indeed Object doesn't have `findIndex` method that [Array](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Array/findIndex) has.

As well choices should be an `Array`

**Comment by mtriff** [comment]
You can give v9.1.0 a try, a couple of IE11-related bug fixes were included.

Microsoft has announced that [IE11 will be retired mid-2022](https://techcommunity.microsoft.com/t5/windows-it-pro-blog/internet-explorer-11-desktop-app-retirement-faq/ba-p/2366549). IE11 also now has well under 1% of browser usage. I don't plan to devote time to troubleshooting and resolving IE11-related issues.

Reasonable PRs will be accepted.
