### ISSUE TITLE
Odd (broken ?) text search behaviour

### ISSUE THREAD

**Issue by inspector71** [Choices-js/Choices#810]
Hello

Thank you for your efforts writing this module and open sourcing it.

Unfortunately, when testing the 'latest' (`9.0.1` ?) version, I type `lend` and the following option is returned:

`-3- Industrial (170769) > Farming & Agriculture (11748) > Food Dehydrators (170763)`

... whilst this is filtered out:

`-3- Baby (2984) > Feeding (20400) > Food Grinders & Blenders (32866)`

---

Also, simply typing "blenders" or "Blenders" fails to return the above option.

Perhaps an issue with handling entitized (`&amp;`) ampersands in `<option>` text?

**Comment by mtriff** [comment]
Choices uses the Fuse.js library to handle searching. By default, Fuse only checks the first 60 characters. You can get the match working by setting the distance option to a higher value, for example:

```
const choices = new Choices('#yourSelectElement', {
  choices: yourChoices,
  fuseOptions: {
    distance: 400
  }
});
```

What you probably want is to use Fuse's `ignoreLocation` option, but the current version of Fuse bundled with Choices does not support it.

You can monitor #881 for when ignoreLocation will be available.
