### ISSUE TITLE
Bug in IE 11 with fetch

### ISSUE THREAD

**Issue by Gougoul** [Choices-js/Choices#815]
In IE 11, I have a choice that is filled that way 

const participantChoices = new Choices(elt, {removeItemButton: false, shouldSort: true});
        
        var loadChoices = function() {
	            const headers = {
	                "Content-Type": "application/json",
	                "Access-Control-Origin": "*"
	            };
	            return fetch('/api/data.json', {
	                method: 'POST',
	                headers: headers,
	                body: JSON.stringify(filter)
	            })
	            .then(function (response) {
	            	
	            	var json = response.json();	            	
	                return json;
	            });
    	};        
        elt.addEventListener('showDropdown', function(event) {        	     
        	participantChoices.setChoices(loadChoices,'value','label',true);    		
        });

It doesn't work the very first time you open the choice (it loads and closes right after), 
but afterwards, it runs everytime perfectly...

Any idea (Seems to work with Edge) ?

**Comment by Gougoul** [comment]
This is the polyfill used 
<script src="https://cdn.polyfill.io/v2/polyfill.js?features=es5,Element.prototype.closest,Array.prototype.findIndex,Array.prototype.find,Array.prototype.map,Array.prototype.some,fetch,Element.prototype.classList,requestAnimationFrame,Node.insertBefore,Node.firstChild,CustomEvent,Array.prototype.includes,Array.from,Array.prototype.reduce,Array.prototype.indexOf"></script>

**Comment by Gougoul** [comment]
Hi sorry to bring this issue back to life, but could you give it a look ?

**Comment by mtriff** [comment]
You can give v9.1.0 a try, a couple of IE11-related bug fixes were included.

Microsoft has announced that [IE11 will be retired mid-2022](https://techcommunity.microsoft.com/t5/windows-it-pro-blog/internet-explorer-11-desktop-app-retirement-faq/ba-p/2366549). IE11 also now has well under 1% of browser usage. I don't plan to devote time to troubleshooting and resolving IE11-related issues.

Reasonable PRs will be accepted.
