### ISSUE TITLE
400 items - Performance issues - Slow

### ISSUE THREAD

**Issue by alvarotrigo** [Choices-js/Choices#816]
**Describe the bug**

With a list of 400 issues I experiement performance issues when working with the single select box when:

- Searching for a text 
- Clicking on an element (takes more than expected to hide the item)

**To Reproduce**
Go here: https://codepen.io/alvarotrigo/pen/PowgMmw
Search for a text such as "flkjadslkfjaslfjlakjf"
Or just click on any item in the list, you'll notice how it doesn't close as fast as expected.

**Screenshots**
See a video here:
![video](https://user-images.githubusercontent.com/1706326/73286319-a89fe480-41f7-11ea-8c62-b2ebc57e1576.gif)

**Desktop (please complete the following information):**
 - OS: latest Mac OS X Catalina 10.15.2
 - Browser Chrome
 - Version: lastest Chrome version  79.0

**Comment by alvarotrigo** [comment]
Just as a node.
The same list seems to work smoothly in Select2. So I assume the issue can be dealt with somehow.

**Comment by abarrak** [comment]
Still an issue in choicesJS @alvarotrigo ..
I wonder weather the root cause the highlight behavior and how to disable it ..

**Comment by Xon** [comment]
This appears to be something todo with the css/html for the select-select mode. The multi-select works fine.

I actually prefer the multi-select even for single item, so I've hacked that into my own fork. The documentation (and config name) will need some cleanup.

**Comment by Xon** [comment]
There was an O(N^2) behavior in search, since `v11.0.0-rc8` was deployed it looks to be working better.

There is a stall when stopping search, but an that is because it is re-rendering all the choices
