### ISSUE TITLE
BUG: 'choices__list--dropdown' class missing in IE11

### ISSUE THREAD

**Issue by ababic** [Choices-js/Choices#834]
**Describe the bug**

Use of `classList.add()` with multiple arguments results in the `'choices__list--dropdown'` class not being added in IE11, making things appear very broken:
https://github.com/jshjohnson/Choices/blob/68313da4122ec7f76274b22926e762914c96723d/src/scripts/templates.ts#L286

**To Reproduce**
Open any example in IE11 using the latest version, and you should see the search input and choices displayed directly below the field. Add the `'choices__list--dropdown'` class directly to the correct in question using developer tools, and everything works fine.

**Screenshots**

<img width="564" alt="Screenshot 2020-03-02 at 7 47 07 am" src="https://user-images.githubusercontent.com/7779588/75655609-24a7a500-5c5a-11ea-8911-5c5d63db4da6.png">

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: IE11
 - Version Latest

**Additional context**

**Comment by tsharms** [comment]
You can fix it with adding a polyfill for Element.classtlist. It's because ie11 doesn't support multiple parameters with the add and remove methods.

Example polyfill:
https://polyfill.io/v3/polyfill.min.js?features=Element.prototype.classList

**Comment by ababic** [comment]
@tsharms thanks. That's exactly what I went with in the end. I just feel it's a shame to have to use a polyfill to circumvent this. This plugin is otherwise carefully written (it appears that this is the only place where IE11 support falls short), and there are other ways to update element classes that wouldn't have this problem.
