### ISSUE TITLE
IE11 detection is not working

### ISSUE THREAD

**Issue by nmutsanas** [Choices-js/Choices#835]
**Describe the bug**
The library fails to detect that it is running on IE11.
**To Reproduce**
The check of running on IE11 is as follows:
`const IS_IE11 =  '-ms-scroll-limit' in document.documentElement.style &&  '-ms-ime-align' in document.documentElement.style; 
`
Test the first half of the condition in IE11's console:
`'-ms-scroll-limit' in document.documentElement.style`
returns false
`'msScrollLimit' in document.documentElement.style`
returns true

(similar for the other half of the condition: `-ms-ime-align`)

**Expected behavior**
Detect IE11 more reliably

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser IE 11.0.170
 - Version 11.0.9600.19596CO

**Comment by mtriff** [comment]
You can give v9.1.0 a try, a couple of IE11-related bug fixes were included.

Microsoft has announced that [IE11 will be retired mid-2022](https://techcommunity.microsoft.com/t5/windows-it-pro-blog/internet-explorer-11-desktop-app-retirement-faq/ba-p/2366549). IE11 also now has well under 1% of browser usage. I don't plan to devote time to troubleshooting and resolving IE11-related issues.

Reasonable PRs will be accepted.
