### ISSUE TITLE
How to add button select all and deselect all on multiple select?

### ISSUE THREAD

**Issue by Lukaum** [Choices-js/Choices#841]
I need to select all and deselect all butttons on multiple select (inside).  Have implemented on this plugin? How can i do this?

**Comment by mtriff** [comment]
This isn't implemented within the library, but you can implement this using a combination of [setChoiceByValue(value)](https://github.com/Choices-js/Choices#setchoicebyvaluevalue) and [removeActiveItems(excludedId)](https://github.com/Choices-js/Choices#removeactiveitemsexcludedid).
