### ISSUE TITLE
Exclude Fuse.js library if not using search

### ISSUE THREAD

**Issue by jonnymaceachern** [Choices-js/Choices#849]
- I'm not using the fuzzy search feature.
- I am using Babel and importing it like so: `import Choices from 'choices.js';`

 Is it possible to import Choices.js without Fuse.js?

**Comment by mtriff** [comment]
Unfortunately, this isn't possible with how Choices is currently designed. 

In the future I'd like to separate individual components to allow for Fuse to be removed via tree-shaking with Webpack or Rollup, but it will require a major refactoring and isn't planned for the short-term.

**Comment by midzer** [comment]
@jonnymaceachern check out my fork (without fuse.js) https://github.com/midzer/Choices

**Comment by Xon** [comment]
I plan to have v11.0.0 should different exports for the package;
```
choices.min.js: 20.36KB
choices.search-basic.min.js: 19.31KB
choices.search-prefix.min.js: 15.27KB
```
