### ISSUE TITLE
Select search input not being reset if value is cut (Ctrl+x)

### ISSUE THREAD

**Issue by evenfrost** [Choices-js/Choices#860]
**Describe the bug**
Select search input won't be resetted if the value entered is cut with Ctrl+x (instead of removing via Backspace/Delete button)

**To Reproduce**
1. Go to https://joshuajohnson.co.uk/Choices/.
2. Scroll down to 'Multiple select input'.
3. Input any value in search box.
4. Select the value and cut it (Ctrl+a, Ctrl+x).

**Expected behavior**
The search is reset to initial state.

**Comment by Xon** [comment]
Implemented as part of #1166
