### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by mpreziuso** [Choices-js/Choices#880]
Hi @jshjohnson , I've noticed this project and found it extremely useful (especially since there's no dependency on jQuery), but also noticed there haven't been any new releases since Nov last year and no commits since January.
So it got me wondering whether including it in new project is a sensible idea:
* Is this project being actively maintained?
* Is there any funding or purely community driven?
* Is there a roadmap?

Thanks

**Comment by kroehre** [comment]
@jshjohnson may I suggest soliciting maintainers for this project? You've done great work here but issues and PRs are stacking up.

**Comment by jshjohnson** [comment]
I have updated the README requesting maintainers: https://github.com/jshjohnson/Choices/blob/master/README.md 👍

**Comment by deepj** [comment]
@jshjohnson has any one been selected?

**Comment by mtriff** [comment]
Hey, I'm a new maintainer on the project. No roadmap but my primary focus will be on merging PRs, cleaning up the issues backlog and updating dependencies. I think the library is great as is and don't plan to make big changes, but pull requests are welcome!

**Comment by midzer** [comment]
I've updated some dependencies in my fork (+ some more changes) https://github.com/midzer/Choices

Testing is broken though...

**Comment by Xon** [comment]
I've taken over maintenance, I've been looking through various backlogs and addressing issues. The v11.0.0 release has had a lot of code churn, but all the tests are working and I'm looking through for more bugs to fix.

@midzer would you be willing to open a PR to submit your search implementation and I can add it as a bundle that is built with the other search variants? It should be fairly simple to plumb in now.

**Comment by midzer** [comment]
@Xon I wonder whether implementing a custom KMP search like https://github.com/midzer/choices/blob/9d96422811ff4bfe8d1b71f3f2f685211489e5b1/src/scripts/choices.ts#L1318 is worth it.

While checking your changes in `SearchByPrefixFilter` class, I realized you use `.startsWith()` over `_haystack`. According to https://gist.github.com/blasten/d42bd0d814b7df1addea?permalink_comment_id=4398245#gistcomment-4398245 (referencing to `indexOf`), `startsWith()` is *probably* not slower than a custom implementation.

**Comment by Xon** [comment]
Maybe adding a config toggle so the prefix search supports `.indexOf` would be worth it.

But if `.indexOf` or `.startsWith` are implemented using something like KMP or another optimized algo, then I don't think it would be worth re-implementing those.

**Comment by midzer** [comment]
Let's leave this in consideration for the future if any performance issues occur for large data sets.

Looking forward to test this Choices.js v11 version for one of my projects, where I have ~10k+ entries.

Thanks for your work in keeping this project alive, changes seem to be good :)

**Comment by Xon** [comment]
I've actually working on some performance related fixes in #1170. Improving item rendering was easy enough but choices (aka options) needs more work due to the various features which result in the entire list being rebuild more often

**Comment by midzer** [comment]
After trying out v11 in one of my projects, I realized `startsWith()` is different to the custom KMP algorithm:

KMP works like `indexOf()` as quoted in a link earlier in contrast to `startsWith()`. So, it makes definitely sense to include it here next to the Fuse.js fuzzy search.

I would like to contribute KMP in this upstream repo in order to archive https://github.com/midzer/Choices in the long run.

**Comment by Xon** [comment]
Adding an `indexOf()` variant should be quite trivial, but adding a KMP implementation is also fine. I'll keep an eye out for any pull requests.
