### ISSUE TITLE
Multiple select input doesn’t work on Internet Explorer 11

### ISSUE THREAD

**Issue by supermueller** [Choices-js/Choices#887]
**Describe the bug**
Multiple select input doesn’t work on Internet Explorer 11. All choices are shown below the input field permanently.

**To Reproduce**
1. Open the [demo](https://joshuajohnson.co.uk/Choices/) in Internet Explorer 11.

**Expected behavior**
The choices should be displayed in a dropdown when the input is focused.

**Screenshot**
![image](https://user-images.githubusercontent.com/2378496/89538319-b2378400-d7fa-11ea-81c6-6be4991c0e76.png)

**Found issues**
- Internet Explorer 11 doesn’t support the CSS property `inital` (see [Can I use...](https://caniuse.com/#feat=css-initial-value)) which is used to hide the list with choices.
- In Internet Explorer 11 the modifier class `choices__list--dropdown` is missing. 

**Workaround**
Add the following Sass code:

```
.choices.is-open {
    overflow: visible;
}

.choices__list[aria-expanded] {
    @extend .choices__list--dropdown;
}
```

**Comment by mtriff** [comment]
Microsoft has announced that [IE11 will be retired mid-2022](https://techcommunity.microsoft.com/t5/windows-it-pro-blog/internet-explorer-11-desktop-app-retirement-faq/ba-p/2366549). IE11 also now has well under 1% of browser usage. I don't plan to devote time to troubleshooting and resolving IE11-related issues.

That said, it looks like you have a solution here, if there aren't any negative side effects, a PR would be accepted.
