### ISSUE TITLE
Results contain unexpected results

### ISSUE THREAD

**Issue by mohamedsabil83** [Choices-js/Choices#895]
**Describe the bug**
When I start writing what I need to search, I got also results which not contains what I typed. It happens also in the [demo](https://joshuajohnson.co.uk/Choices)

**To Reproduce**
1. Go to [demo](https://joshuajohnson.co.uk/Choices)
2. Click on any single select dropdown let's assume 'cities'
3. Start typing 'lo'
4. You will get 'London' and 'Leeds'

**Expected behavior**
Just show 'London' as 'Leeds' doesn't contain 'lo' which typed to search

**Comment by mukeshkdangi** [comment]
This actually is really big issue and should be resolved soon. Bokeh guys is using this lib and this bug has forced me come here to inform you guys :(

**Comment by peterbormans** [comment]
Are you sure this is actually a bug?

Under the hood Choices uses fuse.js as it's search engine. Fuse.js provides fuzzy search functionality and the results of fuzzy searches don't always seem intuitive.

I was able to reproduce the effects as described above. And then I was able to reproduce the 'expected' effect by changing the fuse.js configuration from within the configuration for choices. Like so

> let options = {
>    ...
>    fuseOptions: { threshold: 0.0 }
> };
> new Choices('#select_id', options);

The option `threshold: 0.0` effectively removes the 'fuzzyness' from the search and yields more intuitive results. You can fine more options in [https://fusejs.io/api/options.html](https://fusejs.io/api/options.html)

Hope this helps.
