### ISSUE TITLE
Remove stray console.log

### ISSUE THREAD

**Issue by timrosskamp** [Choices-js/Choices#897]
https://github.com/jshjohnson/Choices/blob/68313da4122ec7f76274b22926e762914c96723d/src/scripts/choices.ts#L2261

There is a stray `console.log()` in the production code. This can bloat the console if many options get initialized.

**Comment by JiveDig** [comment]
Was debugging for a while until I found this. I thought I had an issue with my config. 

Note, this is unaffected by the `silent: false,` property.

**Comment by mtriff** [comment]
This has been resolved in version 9.1.0.
