### ISSUE TITLE
Why is there no example of using XHR/Ajax?

### ISSUE THREAD

**Issue by notflip** [Choices-js/Choices#914]

**Comment by Grafikart** [comment]
If someone find this issue here is an example.

```js
choices.passedElement.element.addEventListener(
          'search',
          debounce(async e => {
            const data = await jsonFetch(`${this.dataset.search}?q=${encodeURIComponent(e.detail.value)}`)
            this.choices.setChoices(data, this.dataset.value || 'value', this.dataset.label || 'label', true)
          }, 400)
        )
```

**Comment by tjwelde** [comment]
We are using it similar to the Example 2 in the Readme: https://github.com/jshjohnson/Choices#setchoiceschoices-value-label-replacechoices. Do you need more than that?

**Comment by rifton007** [comment]
What is `this.dataset`, because for me is undefined ? 

> ```js
> choices.passedElement.element.addEventListener(
>     'search',
>     debounce(async e => {
>         const data = await jsonFetch(`${this.dataset.search}?q=${encodeURIComponent(e.detail.value)}`)
>         this.choices.setChoices(data, this.dataset.value || 'value', this.dataset.label || 'label', true)
>     }, 400)
> )
> ```

**Comment by mik13ST** [comment]
There is a demo of _remote source_ usage at https://joshuajohnson.co.uk/Choices/#choices-single-remove-xhr. The `setChoices()` also takes a function that returns the items which makes it easy to implement this without handling any events. See the docs for details.

This is the relevant code from the demo:
```js
        var singleXhrRemove = new Choices('#choices-single-remove-xhr', {
          removeItemButton: true,
          searchPlaceholderValue: "Search for a Smiths' record",
        }).setChoices(function(callback) {
          return fetch(
            'https://api.discogs.com/artists/83080/releases?token=QBRmstCkwXEvCjTclCpumbtNwvVkEzGAdELXyRyW'
          )
            .then(function(res) {
              return res.json();
            })
            .then(function(data) {
              return data.releases.map(function(release) {
                return { label: release.title, value: release.title };
              });
            });
        });

```

I recommend using ES7 `await` instead of the `.then()` thought.

I agree, there could be an example that illustrates this more clearly.

**Comment by rizkhal** [comment]
I have search with ajax 
```js
el.addEventListener("search", _.debounce(async (event) => {
        let data = await getOptions(`${url}?q=${event.detail.value}`);

        select.setChoices(data, "value", "label", false);
    }, 1000)
);
```

but every i delete the keyword on search field, the last key not removed
![Screenshot from 2022-01-02 14-44-48](https://user-images.githubusercontent.com/24653114/147867416-a883baef-381d-4c82-a9f1-3dc42bc62597.png)
