### ISSUE TITLE
Dynamically push new properties to existing Choices

### ISSUE THREAD

**Issue by bgp1** [Choices-js/Choices#915]
Hello,

An example I have a select that has 5 options to pick from. By default I want the user to be able to select 0 to 5 of these options. But if they change something else on the form, say a checkbox, I want to dynamically push the `maxItemCount` from -1 (default) to 1. If they then uncheck that checkbox I want to dynamically push `maxItemCount` back to -1. Don't see anything in the docs that supports pushing properties using a setter. Does this exist?

**Comment by mtriff** [comment]
You can update the configuration directly at any time like so:
```
choicesInstance.config.maxItemCount = 1;
```
