### ISSUE TITLE
Add image

### ISSUE THREAD

**Issue by bronewi4ok** [Choices-js/Choices#916]
Is there a way to add images to this beautiful plugin? I would like to select languages with flag images, but I haven't found an option for that.

**Comment by abinoda** [comment]
+1

**Comment by mectorfector** [comment]
simply set the html for the image in the label value of the choice

**Comment by mtriff** [comment]
> simply set the html for the image in the label value of the choice

This is the correct approach.

**Comment by Dibbyo456** [comment]
An example please? If I want to add the below image in the option field of UK, how do I do that?

`<img src="https://img.icons8.com/emoji/48/000000/united-kingdom-emoji.png"/>`

````html
<select class="form-control choices-single">
    <option value="UK">UK</option>
</select>
````

**Comment by mtriff** [comment]
I need to experiment more, but I believe you need to use [custom templates](https://github.com/Choices-js/Choices#callbackoncreatetemplates) if you want to load an image with the options in HTML. You can use the JavaScript interface like this:
```html
<select id="choices-images" class="form-control choices-single">
  <option value=""></option>
</select>
```
```javascript
const values = [{
  value: 'UK',
  label: '<img src="https://img.icons8.com/emoji/48/000000/united-kingdom-emoji.png"/> UK',
  id: 1
}]

const element = document.querySelector('#choices-images');
const choices = new Choices(element, {
  choices: values,
  allowHTML: true
});
```

**Comment by leonvukovic** [comment]
Nice one! :beers:
