### ISSUE TITLE
I don't know where to set the input type

### ISSUE THREAD

**Issue by conor909** [Choices-js/Choices#922]
The docs dont say where to set the input type ie: text | select-one | select-multiple

Therefore I get the following error from copying the examples:
`Expected one of the following types text|select-one|select-multiple`

The example code from the docs:
```
const element = document.querySelector('.my-div-selector');
const choices = new Choices(element);
```

**Comment by rp3r** [comment]
It looks like the types are data-types (`data-type="text | select-one | select-multiple"` but I only got that error when passing an jQuery object to `new Choices()`.
Did you try to pass any options?

**Comment by long2ice** [comment]
Just like `<select multiple class="form-select"><select>`

**Comment by mtriff** [comment]
Your selector must match one of the elements listed [here](https://github.com/Choices-js/Choices#input-types).

**Comment by Himanshu-Khanna** [comment]
Hi I am getting same issue even after adding the multiple in the select feild

`<select class="form-control select-location js-media" multiple id="js-media-choice" name="media_source[]" data-parsley-error-message="Select source" data-parsley-required="data-parsley-required">`
