### ISSUE TITLE
Bug found on scrollable 'SELECT' component

### ISSUE THREAD

**Issue by wag110894** [Choices-js/Choices#933]
**Describe the bug**

Testing out the UI on IE11 and it seems that the scrollable ‘SELECT’ component will close on it’s on upon clicking on the up and down buttons to scroll the list.
Further investigation shows that the scrollable ‘SELECT’ component will close on it’s own. 

**To Reproduce**
1. Use https://formio.github.io/formio.js/app/examples/select.html
2. Try scrolling the list of Values by clicking the up and down buttons to scroll the list.
3. When scrolling, it will hide the list and just show the item that it is on.

**Expected behavior**
Able to use the up and down buttons to scroll the list
**Screenshots**
https://share.getcloudapp.com/eDu8X4EX

**Comment by wag110894** [comment]
Any update on this issue?

**Comment by mtriff** [comment]
You can give v9.1.0 a try, a couple of IE11-related bug fixes were included.

Microsoft has announced that [IE11 will be retired mid-2022](https://techcommunity.microsoft.com/t5/windows-it-pro-blog/internet-explorer-11-desktop-app-retirement-faq/ba-p/2366549). IE11 also now has well under 1% of browser usage. I don't plan to devote time to troubleshooting and resolving IE11-related issues.

Reasonable PRs will be accepted.
