### ISSUE TITLE
Show avatar in select (when selected)

### ISSUE THREAD

**Issue by samuelsylvander** [Choices-js/Choices#936]
If an avatar is specified like in the example below, then it would be nice to also see it when selected. Now only the label is shown when selected.

code example:
`{
    "value": "1",
    "label": "My Choice",
    "customProperties": {
    "avatarSrc": "../assets/img/icon-mychoice.svg"
    }
}`

This will output:
`<div class="choices__item is-highlighted" data-item="" data-id="1" data-value="1" data-custom-properties="[object Object]" aria-selected="true" data-deletable="">My Choice</div>`

Would be nice if the output was:
```
<div class="choices__item is-highlighted" data-item="" data-id="1" data-value="1" data-custom-properties="[object 
Object]" aria-selected="true" data-deletable="">
    <div class="avatar avatar-xs me-3">
        <img class="avatar-img rounded-circle" src="../assets/img/icon-mychoice.svg" alt="My Choice">
    </div>
    My Choice
</div>
```

**Comment by mectorfector** [comment]
simply set the avatar html in the choice label itself, worked for me

**Comment by samuelsylvander** [comment]
Do you have the example code for that please?

**Comment by Dibbyo456** [comment]
An example can be found here https://github.com/Choices-js/Choices/issues/916#issuecomment-1009981879
