### ISSUE TITLE
Need to add btn "add all", or "remove all" in multiple select

### ISSUE THREAD

**Issue by IrynaVynnychenko** [Choices-js/Choices#951]
Hello!
Need to add btn "add all", or "remove all" in multiple select
So, when we in multiple select, may to click on 1 btn to choose all of propose items :)
Is it possible to add this?
Or maybe you already have it?

**Comment by FahriDevZ** [comment]
You mean like this example?

https://jsbin.com/taqiradeva/edit?js,output

**Comment by IrynaVynnychenko** [comment]
@FahriDevZ, thanks to you, that's exactly what i meant :)

**Comment by FahriDevZ** [comment]
if all is done, please close this issues 👍
