### ISSUE TITLE
Homepage is down (404)

### ISSUE THREAD

**Issue by kuanyui** [Choices-js/Choices#957]
**Describe the bug**
Demo in https://joshuajohnson.co.uk/Choices/ is down (404 not found)

**To Reproduce**
1. Go to https://joshuajohnson.co.uk/Choices/

**Expected behavior**
1. Can see demo in that page.

**Screenshots**
![Screenshot_20210618_171011](https://user-images.githubusercontent.com/1370070/122537360-0e447900-d058-11eb-8fbc-afb104a1930a.png)

**Desktop (please complete the following information):**
N/A
**Smartphone (please complete the following information):**
N/A
**Additional context**
N/A

**Comment by llui85** [comment]
It's been moved here: https://choices-js.github.io/Choices/
