### ISSUE TITLE
addItemText not working

### ISSUE THREAD

**Issue by manobalansm** [Choices-js/Choices#960]
addItemText
it's not working for me ...

editItems: true,
            addItemText: (value) => {
                return `Press Enter to add <b>"${value}"</b>`;
            },

do i have to add any other extra codes ?

**Comment by FahriDevZ** [comment]
Can you post an error log?

**Comment by mtriff** [comment]
Sorry, there isn't enough information here to reproduce and debug your issue. If you still need assistance, please re-create this issue using the "Bug report" issue template.
