### ISSUE TITLE
Update the .scss file to latest Sass

### ISSUE THREAD

**Issue by creativeDM** [Choices-js/Choices#964]
Hello Team Choices.
I am getting the error from sass when i compiling the imported choices.scss with my style.scss file

Here is what sass says 🙄

`DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div(-$choices-button-offset, 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

    ╷
129 │     margin-right: -$choices-button-offset/2;
    │                   ^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
    node_modules\choices.js\src\styles\choices.scss 129:19  @import
    src\scss\style.scss 15:9`

Please Update the scss file with latest sass version. Its taking the time during development. 

Anyway - Great Plugin and loved to used it 👍

Thanks for making such a beautiful plugin.

**Comment by leereichardt** [comment]
PR already created for this found here https://github.com/Choices-js/Choices/pull/963

**Comment by hans2103** [comment]
instead of using math.div I suggest to use multiplier `*` instead
See #976

**Comment by mtriff** [comment]
Resolved in v9.1.0
