### ISSUE TITLE
Item not returned despite search text matching

### ISSUE THREAD

**Issue by skipcress** [Choices-js/Choices#974]
**Describe the bug**
I'm using a platform called OutSystems, which uses this plugin for searchable comboboxes. I've got a list which contains an element named "_WOMEN'S BUSINESS ENTERPRISE COUNCIL PACIFIC (WBEC PACIFIC) (dba) (ASTRA SOCIETY INTERNATIONAL)_" but when searching with the text "_astra_" no relevant results are found.

**To Reproduce**
1. Create a list containing "_WOMEN'S BUSINESS ENTERPRISE COUNCIL PACIFIC (WBEC PACIFIC) (dba) (ASTRA SOCIETY INTERNATIONAL)_"
2. Search for "_astra_"
3. The record is not found

**Expected behavior**
The record "_WOMEN'S BUSINESS ENTERPRISE COUNCIL PACIFIC (WBEC PACIFIC) (dba) (ASTRA SOCIETY INTERNATIONAL)_" is returned.

**Screenshots**
![image](https://user-images.githubusercontent.com/77211825/141536443-f41d2f0d-ec02-456a-a3e9-527905da6cf2.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version 95.0.4638.69

**Additional context**

**Comment by mtriff** [comment]
Choices uses the [Fuse.js library](https://github.com/krisk/Fuse) to handle searching. By default, Fuse only checks the first 60 characters. I was able to get the match working by setting the `distance` option to 400 like so:
```
const choices = new Choices('#yourSelectElement', {
  choices: yourChoices,
  fuseOptions: {
    distance: 400
  }
});
```

What you probably want is to use Fuse's `ignoreLocation` option, but the current version of Fuse bundled with Choices does not support it.

**Comment by mtriff** [comment]
You can monitor #881 for when `ignoreLocation` will be available.

**Comment by skipcress** [comment]
Thanks very much, mtriff!
