### ISSUE TITLE
Sass Error invalid CSS - expect expression on "color.adjust()"

### ISSUE THREAD

**Issue by Chrico** [Choices-js/Choices#981]
**Describe the bug**
I'm getting following error:

```
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Invalid CSS after "...1px solid color": expected expression (e.g. 1px, bold), was ".adjust($choices-pr"
        on line 149 of node_modules/choices.js/src/styles/choices.scss
>>     border-left: 1px solid color.adjust($choices-primary-color, $lightness:
```

When compiling CSS with following dependencies:

```
"choices.js": "^9.0.1"
"node-sass": "^7.0.0"
"sass-loader": "^12.0.0
"@symfony/webpack-encore": "^1.7.0" // webpack 5
```

----

**To Reproduce**
1. Import `import 'choices.js/src/styles/choices.scss';` in CSS or JS
2. run `yarn encore dev`

**Comment by mtriff** [comment]
Can you try with the latest version of Choices (v9.1.0)? You will likely need to switch from `node-sass` to the [`sass`](https://www.npmjs.com/package/sass) module too (`node-sass` has been deprecated).

**Comment by dessalines** [comment]
Thanks, switching to `sass` fixed this issue.
