### ISSUE TITLE
TypeScript types not published in 9.1.0

### ISSUE THREAD

**Issue by mgmeyers** [Choices-js/Choices#988]
**Describe the bug**
I just upgraded choices from 9.0.1 to 9.1.0 and noticed that `./types/index.d.ts` is not included in the NPM package.

**To Reproduce**
Install version `9.1.0` and look in the `node_modules` folder. There is no `types` folder.

**Expected behavior**
`./types/index.d.ts` should be included in the package

**Comment by mtriff** [comment]
This has been fixed on `master`. I expect to release a new version in the next week or so. For now you can use the master branch directly (it's stable):
```
npm install Choices-js/Choices#master
```
