### ISSUE TITLE
allowHTML not working

### ISSUE THREAD

**Issue by htdung83** [Choices-js/Choices#994]
I have placed HTML element to option text and set allowHTML into true but the displayed text was not break down.

<select>
  <option value="1">ABC <br> abc</option>
  <option value="2">XYZ <br> xyz</option>
</select>

<script>
let choice = new Choices('select', {
  allowHTML: true
});
</script>

**Comment by mtriff** [comment]
Please provide the exact code (HTML and JavaScript) you are using so that we can duplicate the issue.

**Comment by htdung83** [comment]
> Please provide the exact code (HTML and JavaScript) you are using so that we can duplicate the issue.

Sorry now I know my issue was that I didn't input a choices array. I didn't know that it can't get choices from the Option elements of the Select element. Hope it will be improved for next version.
